//! One module per step, private to this directory: a step reaches the runner
//! and the checks, never another step. Each module declares its steps as
//! data, `STEPS`; `run` and `describe` are the two doors in.

use crate::runner::{Failure, Outcome, Step, enter};
use std::fmt::Write as _;

mod attest_binaries;
mod binary_hardening;
mod configure_cargo_registry;
mod declared_msrv;
mod dependency_policy;
mod feature_combinations;
mod format_lint_test;
mod fuzz_regression;
mod install_toolchain;
mod install_tools;
mod line_coverage;
mod mutation_testing;
mod publish_binaries;
mod publish_crate;
mod publish_evidence;
mod quality_scorecard;
mod recorded_audits;
mod release_build;
mod report_duplicates;
mod report_sizes;
mod require_every_check;
mod secret_scan;
mod stage_payload;
mod unsafe_audit;
mod unused_dependencies;
mod validate_inputs;
mod verify_payload;
mod vulnerability_audit;

/// Every step of every workflow, in the order the workflows run them:
/// `ci.yml` first, then the commands several workflows share, then the other
/// workflows.
const REGISTRY: &[&[Step]] = &[
    validate_inputs::STEPS,
    configure_cargo_registry::STEPS,
    install_toolchain::STEPS,
    format_lint_test::STEPS,
    report_sizes::STEPS,
    report_duplicates::STEPS,
    line_coverage::STEPS,
    vulnerability_audit::STEPS,
    dependency_policy::STEPS,
    mutation_testing::STEPS,
    secret_scan::STEPS,
    declared_msrv::STEPS,
    feature_combinations::STEPS,
    unused_dependencies::STEPS,
    recorded_audits::STEPS,
    release_build::STEPS,
    binary_hardening::STEPS,
    stage_payload::STEPS,
    quality_scorecard::STEPS,
    require_every_check::STEPS,
    install_tools::STEPS,
    verify_payload::STEPS,
    publish_binaries::STEPS,
    publish_crate::STEPS,
    publish_evidence::STEPS,
    attest_binaries::STEPS,
    fuzz_regression::STEPS,
    unsafe_audit::STEPS,
];

/// Every registered step, in registry order.
fn steps() -> impl Iterator<Item = &'static Step> {
    REGISTRY.iter().flat_map(|steps| steps.iter())
}

/// Run the step `command` names: `ci.yml` steps and the shared commands are
/// one word, the other workflows name themselves first. The step is entered
/// before it runs, so the runner refuses what it did not declare.
pub(crate) fn run(command: &str, step: &str) -> Outcome {
    let (workflow, id) = if step.is_empty() {
        ("", command)
    } else {
        (command, step)
    };
    let found = steps().find(|candidate| {
        candidate.id == id
            && (candidate.workflow == workflow
                || workflow.is_empty() && matches!(candidate.workflow, "ci" | "shared"))
    });
    let Some(found) = found else {
        return Err(Failure::from(format!(
            "unknown gate command: {}",
            [command, step].join(" ").trim()
        )));
    };
    enter(found)?;
    (found.run)()
}

/// The steps as a document, one table per workflow, generated so that what a
/// step declares and what a reader is told cannot differ.
pub(crate) fn describe() -> String {
    let mut text = String::from(
        "# The steps\n\nGenerated by `rust-gate describe`; `just docs` rewrites this file and a \
         test refuses a stale copy. Every step, what it reads, runs and writes, from the \
         declaration the gate enforces while the step runs: an input, a tool or a report \
         the step did not declare is refused. The runner's own files and the job's \
         directories are read by every step and not listed.\n",
    );
    let mut workflow = "";
    for step in steps() {
        if step.workflow != workflow {
            workflow = step.workflow;
            let _ = write!(
                text,
                "\n## {workflow}\n\n| Step | What it does | Inputs | Tools | Reports |\n\
                 | --- | --- | --- | --- | --- |\n"
            );
        }
        let _ = writeln!(
            text,
            "| `{}` | {} | {} | {} | {} |",
            step.id,
            step.summary,
            cell(step.inputs),
            cell(step.tools),
            cell(step.reports)
        );
    }
    text
}

/// A table cell listing names, or empty.
fn cell(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("`{name}`"))
        .collect::<Vec<_>>()
        .join(", ")
}
