//! `rust-gate pull-request`: the rules a pull request is held to as a whole,
//! read from its change against the base branch. PRL-001 refuses a `feat` or
//! `fix` pull request that changes product Rust code and touches no test: no
//! file under a `tests` directory and no line inside a `cfg(test)` item,
//! which makes a failing test first a fact the gate can check. PRL-002 reports
//! a pull request over 400 changed lines, lockfiles, snapshots and generated
//! files left out, and refuses nothing. PRL-003 refuses a title that is not a
//! conventional header and PRL-004 a head branch outside `<type>/<name>` and
//! the bots' branches; `hygiene.yml` holds a repository without Rust to the
//! same two.

use crate::checks::pull_request::{
    added_lines, name_findings, pull_request_diff, title_type, touched_lines,
};
use crate::checks::rust_code::{blanked, items, line_at};
use crate::runner::{Failure, Job, Outcome, Step, input, optional, output, summary, write};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

/// What this step declares: its inputs, its tools and its reports.
pub(crate) const STEPS: &[Step] = &[Step {
    workflow: "ci",
    id: "pull-request",
    summary: "Pull request rules PRL",
    inputs: &[
        "GITHUB_BASE_REF",
        "GITHUB_HEAD_REF",
        "GITHUB_WORKSPACE",
        "PULL_REQUEST_TITLE",
    ],
    tools: &["git"],
    reports: &["pull-request.txt"],
    run,
}];

/// The most changed lines PRL-002 lets pass without a word.
const SURGICAL: usize = 400;

/// The directories whose Rust is not product code.
const NOT_PRODUCT: &[&str] = &["tests", "benches", "examples"];

/// Run the step.
fn run() -> Outcome {
    let job = Job::current()?;
    let report = job.report("pull-request.txt")?;
    if optional("GITHUB_BASE_REF")?.is_empty() {
        write(
            &report,
            b"NOT APPLICABLE: a push has no base to compare with\n",
            false,
        )?;
        return output("applied", "false");
    }
    output("applied", "true")?;
    let workspace = PathBuf::from(input("GITHUB_WORKSPACE")?);
    let diff = pull_request_diff(&workspace)?;
    let changed = measured_size(&touched_lines(&diff), &workspace);
    let mut text =
        format!("{changed} changed lines, lockfiles, snapshots and generated files left out\n");
    if changed > SURGICAL {
        let _ = writeln!(
            text,
            "PRL-002 {changed} changed lines, over {SURGICAL}; reported, not refused: split the \
             change where it splits"
        );
    }
    let title = optional("PULL_REQUEST_TITLE")?;
    let kind = title_type(&title).unwrap_or_default();
    let product = product_files(&touched_lines(&diff));
    let untested = matches!(kind, "feat" | "fix")
        && !product.is_empty()
        && !touches_tests(&added_lines(&diff), &touched_lines(&diff), &workspace);
    if untested {
        let _ = writeln!(
            text,
            "PRL-001 a {kind} pull request changes product code ({}) and touches no test; add \
             the test that fails without the change",
            product.join(", ")
        );
    }
    let names = name_findings(&title, &optional("GITHUB_HEAD_REF")?);
    for finding in &names {
        let _ = writeln!(text, "{finding}");
    }
    write(&report, text.as_bytes(), false)?;
    summary(&format!("## Pull request rules\n\n{text}"))?;
    let mut refusals = names;
    if untested {
        refusals.push(format!(
            "a {kind} pull request changes product code and touches no test (PRL-001); \
             pull-request.txt names the files"
        ));
    }
    if refusals.is_empty() {
        return Ok(());
    }
    Err(Failure::from(format!(
        "pull-request: {}",
        refusals.join("; ")
    )))
}

/// The changed lines that count toward PRL-002: every file's but lockfiles,
/// snapshots and the files `rust-gate sync` generates.
fn measured_size(touched: &BTreeMap<String, usize>, workspace: &Path) -> usize {
    touched
        .iter()
        .filter(|(file, _)| {
            let extension = Path::new(file)
                .extension()
                .and_then(|extension| extension.to_str())
                .map(str::to_ascii_lowercase);
            let lock = matches!(extension.as_deref(), Some("lock" | "snap"));
            let generated = fs::read_to_string(workspace.join(file))
                .is_ok_and(|text| text.starts_with("# generated by rust-gate sync"));
            !lock && !generated
        })
        .map(|(_, count)| count)
        .sum()
}

/// The product Rust files among `touched`: Rust outside a tests, benches or
/// examples directory.
fn product_files(touched: &BTreeMap<String, usize>) -> Vec<String> {
    touched
        .keys()
        .filter(|file| {
            Path::new(file)
                .extension()
                .is_some_and(|extension| extension == "rs")
                && !file.split('/').any(|part| NOT_PRODUCT.contains(&part))
        })
        .cloned()
        .collect()
}

/// Whether the change touches a test: a file under a tests directory, or an
/// added line inside a `cfg(test)` item of a Rust file.
fn touches_tests(
    added: &BTreeMap<String, Vec<usize>>,
    touched: &BTreeMap<String, usize>,
    workspace: &Path,
) -> bool {
    if touched
        .keys()
        .any(|file| file.split('/').any(|part| part == "tests"))
    {
        return true;
    }
    added.iter().any(|(file, lines)| {
        let Ok(source) = fs::read_to_string(workspace.join(file)) else {
            return false;
        };
        test_lines(&source)
            .iter()
            .any(|(first, last)| lines.iter().any(|line| (first..=last).contains(&line)))
    })
}

/// The first and last line of every top-level `cfg(test)` item.
fn test_lines(source: &str) -> Vec<(usize, usize)> {
    let code = blanked(source);
    items(&code)
        .iter()
        .filter(|item| item.is_test())
        .map(|item| (line_at(&code, item.span.0), line_at(&code, item.span.1)))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{product_files, test_lines, touches_tests};
    use std::collections::BTreeMap;
    use std::path::Path;

    #[test]
    fn product_code_is_rust_outside_the_test_directories() {
        let touched = BTreeMap::from([
            ("src/lib.rs".to_owned(), 2),
            ("tests/it/main.rs".to_owned(), 1),
            ("crates/a/benches/b.rs".to_owned(), 1),
            ("README.md".to_owned(), 1),
        ]);
        assert_eq!(product_files(&touched), ["src/lib.rs"]);
        assert!(touches_tests(
            &BTreeMap::new(),
            &touched,
            Path::new("/nowhere")
        ));
    }

    #[test]
    fn a_test_module_spans_its_lines() {
        let source = "//! A.\nfn a() {}\n\n#[cfg(test)]\nmod tests {\n    fn b() {}\n}\n";
        assert_eq!(test_lines(source), [(4, 7)]);
    }
}
