//! The registry of every step: the declarations in the order the workflows
//! run them, each named by its path so the list reads as the modules it
//! reaches, and the two doors `main.rs` calls, `run` and `describe`.

use crate::runner::{Failure, Outcome, Step, enter};
use std::fmt::Write as _;

/// Every step of every workflow, in the order the workflows run them:
/// `ci.yml` first, then the commands several workflows share, then the other
/// workflows.
const REGISTRY: &[&[Step]] = &[
    super::validate_inputs::STEPS,
    super::configure_cargo_registry::STEPS,
    super::install_toolchain::STEPS,
    super::format_lint_test::STEPS,
    super::report_sizes::STEPS,
    super::report_duplicates::STEPS,
    super::line_coverage::STEPS,
    super::vulnerability_audit::STEPS,
    super::dependency_policy::STEPS,
    super::mutation_testing::STEPS,
    super::api_compatibility::STEPS,
    super::secret_scan::STEPS,
    super::declared_msrv::STEPS,
    super::feature_combinations::STEPS,
    super::unused_dependencies::STEPS,
    super::recorded_audits::STEPS,
    super::release_build::STEPS,
    super::binary_hardening::STEPS,
    super::stage_payload::STEPS,
    super::quality_scorecard::STEPS,
    super::require_every_check::STEPS,
    super::install_tools::STEPS,
    super::verify_payload::STEPS,
    super::publish_binaries::STEPS,
    super::publish_crate::STEPS,
    super::publish_evidence::STEPS,
    super::attest_binaries::STEPS,
    super::fuzz_regression::STEPS,
    super::unsafe_audit::STEPS,
];

/// Every registered step, in registry order.
fn steps() -> impl Iterator<Item = &'static Step> {
    REGISTRY.iter().flat_map(|steps| steps.iter())
}

/// Run the step `command` names: `ci.yml` steps and the shared commands are
/// one word, the other workflows name themselves first. The step is entered
/// before it runs, so the runner refuses what it did not declare.
pub(crate) fn run(command: &str, step: &str) -> Outcome {
    let (workflow, id) = if step.is_empty() {
        ("", command)
    } else {
        (command, step)
    };
    let found = steps().find(|candidate| {
        candidate.id == id
            && (candidate.workflow == workflow
                || workflow.is_empty() && matches!(candidate.workflow, "ci" | "shared"))
    });
    let Some(found) = found else {
        return Err(Failure::from(format!(
            "unknown gate command: {}",
            [command, step].join(" ").trim()
        )));
    };
    enter(found)?;
    (found.run)()
}

/// The steps as a document, one table per workflow, generated so that what a
/// step declares and what a reader is told cannot differ.
pub(crate) fn describe() -> String {
    let mut text = String::from(
        "# The steps\n\nGenerated by `rust-gate describe`; `just docs` rewrites this file and a \
         test refuses a stale copy. Every step, what it reads, runs and writes, from the \
         declaration the gate enforces while the step runs: an input, a tool or a report \
         the step did not declare is refused. The runner's own files and the job's \
         directories are read by every step and not listed.\n",
    );
    let mut workflow = "";
    for step in steps() {
        if step.workflow != workflow {
            workflow = step.workflow;
            let _ = write!(
                text,
                "\n## {workflow}\n\n| Step | What it does | Inputs | Tools | Reports |\n\
                 | --- | --- | --- | --- | --- |\n"
            );
        }
        let _ = writeln!(
            text,
            "| `{}` | {} | {} | {} | {} |",
            step.id,
            step.summary,
            cell(step.inputs),
            cell(step.tools),
            cell(step.reports)
        );
    }
    text
}

/// A table cell listing names, or empty.
fn cell(names: &[&str]) -> String {
    names
        .iter()
        .map(|name| format!("`{name}`"))
        .collect::<Vec<_>>()
        .join(", ")
}
