//! Every managed file of a repository, rendered. The files every repository
//! holds as they are here are this repository's own, read in when the gate is
//! built, so the home of the gate is the one place to change them; the rest
//! are written from the gate's data and the repository's
//! `maestro-quality.toml`.

use super::hooks::commit_hooks;
use super::pin::Pin;
use crate::checks::lint_policy::{clippy_config, with_lint_block};
use crate::checks::nextest_profile::nextest_profile;
use crate::checks::quality_config::QualityConfig;
use std::fmt::Write as _;

/// The line every managed file opens with.
pub(super) const HEADER: &str = "# generated by rust-gate sync; do not edit\n";

/// Editor settings that survive the editor.
const EDITORCONFIG: &str = include_str!("../../../../.editorconfig");

/// How git treats each kind of file.
const GITATTRIBUTES: &str = include_str!("../../../../.gitattributes");

/// The TOML formatter's settings.
const TAPLO: &str = include_str!("../../../../.taplo.toml");

/// The YAML formatter's settings.
const YAMLFMT: &str = include_str!("../../../../.yamlfmt.yml");

/// The Markdown structure every repository holds to.
const RUMDL: &str = include_str!("../../../../.rumdl.toml");

/// The organization's compiler.
const TOOLCHAIN: &str = include_str!("../../../../rust-toolchain.toml");

/// The organization's formatting: rustfmt's own, in the 2024 style.
const RUSTFMT: &str = "style_edition = \"2024\"\n";

/// DEP-001's cargo-deny policy, up to its exceptions.
const DENY: &str = concat!(
    "# DEP-001: one version of each crate, no wildcard requirement, crates.io\n",
    "# alone, and no yanked or unmaintained crate; the licences the organization\n",
    "# reviewed. An exception lives in maestro-quality.toml, with its reason.\n",
    "\n",
    "[graph]\n",
    "all-features = true\n",
    "\n",
    "[licenses]\n",
    "allow = [\n",
    "  \"Apache-2.0\",\n",
    "  \"MIT\",\n",
    "  \"MIT-0\",\n",
    "  \"Unicode-3.0\",\n",
    "  \"Unlicense\",\n",
    "]\n",
    "confidence-threshold = 0.93\n",
    "unused-allowed-license = \"allow\"\n",
    "private = { ignore = true }\n",
    "\n",
    "[advisories]\n",
    "yanked = \"deny\"\n",
    "unmaintained = \"all\"\n",
    "\n",
    "[sources]\n",
    "unknown-registry = \"deny\"\n",
    "unknown-git = \"deny\"\n",
    "allow-registry = [\"https://github.com/rust-lang/crates.io-index\"]\n",
    "\n",
    "[bans]\n",
    "multiple-versions = \"deny\"\n",
    "wildcards = \"deny\"\n",
);

/// Dependabot's settings for one ecosystem, after its `package-ecosystem`.
const WEEKLY: &str = concat!(
    "    directory: /\n",
    "    schedule:\n",
    "      interval: weekly\n",
    "    cooldown:\n",
    "      default-days: 7\n",
);

/// What the gate knows of a repository to render its files.
pub(super) struct Repository {
    /// Whether it builds Rust: a root `Cargo.toml` or `rust-toolchain.toml`.
    pub(super) rust: bool,
    /// Whether it is the home of the reusable workflows, whose `ci.yml`,
    /// Dependabot settings and hooks are its own.
    pub(super) home: bool,
    /// The root manifest and whether it is a workspace root, when there is one.
    pub(super) manifest: Option<(String, bool)>,
    /// What its `maestro-quality.toml` says.
    pub(super) config: QualityConfig,
    /// The release its caller pins, when one is known.
    pub(super) pin: Option<Pin>,
}

/// Every managed file of `repository` and its content, in path order.
pub(super) fn managed_files(repository: &Repository) -> Result<Vec<(String, String)>, String> {
    let mut files: Vec<(&str, String)> = vec![
        (".editorconfig", EDITORCONFIG.to_owned()),
        (".gitattributes", GITATTRIBUTES.to_owned()),
        (".rumdl.toml", RUMDL.to_owned()),
        (".taplo.toml", TAPLO.to_owned()),
        (".yamlfmt.yml", YAMLFMT.to_owned()),
        ("typos.toml", typos(&repository.config.typos)),
    ];
    if !repository.home {
        let pin = repository.pin.as_ref().ok_or(
            "no release to pin: .github/workflows/ci.yml names none; set RUST_WORKFLOWS_PIN to \
             `<commit> v<version>`",
        )?;
        let workflow = if repository.rust {
            caller(pin, &repository.config.ci)
        } else {
            hygiene_caller(pin)
        };
        files.push((".github/dependabot.yml", dependabot(repository.rust)));
        files.push((".github/workflows/ci.yml", workflow));
        let hooks = commit_hooks(HEADER, repository.rust, &pin.version);
        files.push((".pre-commit-config.yaml", hooks));
    }
    if repository.rust {
        let profile = nextest_profile("default", "");
        files.push((".config/nextest.toml", format!("{HEADER}{profile}")));
        files.push(("clippy.toml", format!("{HEADER}{}", clippy_config())));
        files.push(("rust-toolchain.toml", TOOLCHAIN.to_owned()));
        files.push(("rustfmt.toml", format!("{HEADER}{RUSTFMT}")));
        files.push(("deny.toml", deny(&repository.config)));
    }
    if let Some((text, workspace)) = &repository.manifest {
        files.push(("Cargo.toml", with_lint_block(text, *workspace)?));
    }
    let mut files: Vec<(String, String)> = files
        .into_iter()
        .map(|(path, text)| (path.to_owned(), text))
        .collect();
    files.sort();
    Ok(files)
}

/// `deny.toml`: DEP-001's policy and, as cargo-deny's skips, the duplicate
/// versions `maestro-quality.toml` excuses, `path` naming the crate and its
/// version, `windows-sys@0.52`.
fn deny(config: &QualityConfig) -> String {
    let mut text = format!("{HEADER}{DENY}");
    let skips: Vec<_> = config
        .exceptions
        .iter()
        .filter(|exception| exception.rule == "DEP-001")
        .collect();
    if !skips.is_empty() {
        text.push_str("skip = [\n");
        for exception in skips {
            let reason = exception.reason.replace('\\', "\\\\").replace('"', "\\\"");
            let _ = writeln!(
                text,
                "  {{ crate = \"{}\", reason = \"{reason}\" }},",
                exception.path
            );
        }
        text.push_str("]\n");
    }
    text
}

/// `typos.toml`: the words the repository means, each allowed as written.
fn typos(words: &[String]) -> String {
    let mut text = format!(
        "{HEADER}# The words this repository means, from [typos] words in maestro-quality.toml.\n\n\
         [default.extend-words]\n"
    );
    for word in words {
        let _ = writeln!(text, "{word} = \"{word}\"");
    }
    text
}

/// Dependabot: the actions, and Cargo for a Rust repository, weekly with a
/// week's cooldown and conventional titles; the reusable workflows are left
/// to `rust-gate sync`.
fn dependabot(rust: bool) -> String {
    let mut text = format!(
        "{HEADER}version: 2\nupdates:\n  - package-ecosystem: github-actions\n{WEEKLY}    \
         # The organization merges only conventional titles: \"ci(deps): bump ...\".\n    \
         commit-message:\n      prefix: ci\n      include: scope\n    \
         # rust-gate sync moves the organization's reusable workflows.\n    ignore:\n      \
         - dependency-name: Orchestration-Maestro/rust-workflows*\n    groups:\n      \
         actions:\n        patterns: [\"*\"]\n        update-types: [minor, patch]\n"
    );
    if rust {
        let _ = write!(
            text,
            "  - package-ecosystem: cargo\n{WEEKLY}    # \"build(deps): bump ...\", a \
             conventional title the organization accepts.\n    commit-message:\n      prefix: \
             build\n      include: scope\n    groups:\n      cargo:\n        patterns: \
             [\"*\"]\n        update-types: [minor, patch]\n"
        );
    }
    text
}

/// The caller of a repository without Rust: the hygiene workflow at `pin`.
fn hygiene_caller(pin: &Pin) -> String {
    format!(
        concat!(
            "{header}name: CI\n",
            "\"on\":\n",
            "  push:\n",
            "    branches: [main]\n",
            "  pull_request:\n",
            "permissions:\n",
            "  contents: read\n",
            "jobs:\n",
            "  # Keep the job id `hygiene`: the hygiene-required ruleset requires the\n",
            "  # check \"hygiene / Required hygiene\" before any merge to the default branch.\n",
            "  hygiene:\n",
            "    uses: {reference}\n",
            "    permissions:\n",
            "      contents: read\n",
        ),
        header = HEADER,
        reference = pin.reference("hygiene.yml"),
    )
}

/// The caller of the reusable workflows: the gate at `pin` with the inputs
/// `maestro-quality.toml` passes, then the uploads of its reports.
fn caller(pin: &Pin, inputs: &[(String, String)]) -> String {
    let mut with = String::new();
    if !inputs.is_empty() {
        with.push_str("    with:\n");
        for (key, value) in inputs {
            let _ = writeln!(with, "      {key}: {value}");
        }
    }
    let upload = |job: &str, workflow: &str, scope: &str| {
        format!(
            concat!(
                "  {job}:\n",
                "    needs: rust\n",
                "    uses: {reference}\n",
                "    permissions:\n",
                "      contents: read\n",
                "      {scope}\n",
                "    with:\n",
                "      artifact-name: ${{{{ needs.rust.outputs.artifact-name }}}}\n",
            ),
            job = job,
            reference = pin.reference(workflow),
            scope = scope,
        )
    };
    format!(
        concat!(
            "{header}name: CI\n",
            "\"on\":\n",
            "  push:\n",
            "    branches: [main]\n",
            "  pull_request:\n",
            "permissions:\n",
            "  contents: read\n",
            "jobs:\n",
            "  # Keep the job id `rust`: the rust-ci-required ruleset requires the check\n",
            "  # \"rust / Required Rust CI\" before any merge to the default branch.\n",
            "  rust:\n",
            "    uses: {reference}\n",
            "    permissions:\n",
            "      contents: read\n",
            "{with}",
            "  # Clippy and secret-scan findings into the Security tab.\n",
            "{sarif}",
            "  # Coverage and test results into Codecov, logged in through OIDC.\n",
            "{coverage}",
        ),
        header = HEADER,
        reference = pin.reference("ci.yml"),
        with = with,
        sarif = upload(
            "sarif",
            "upload-sarif.yml",
            "security-events: write  # upload SARIF to code scanning"
        ),
        coverage = upload(
            "coverage",
            "upload-coverage.yml",
            "id-token: write  # log in to Codecov without a stored token"
        ),
    )
}

#[cfg(test)]
mod tests {
    use super::super::pin::parse_pin;
    use super::{HEADER, Repository, managed_files};
    use crate::checks::quality_config::QualityConfig;

    /// A Rust repository pinned at `2.0.0`, what `config` says.
    fn repository(config: QualityConfig) -> Repository {
        Repository {
            rust: true,
            home: false,
            manifest: Some(("[package]\nname = \"a\"\n".to_owned(), false)),
            config,
            pin: parse_pin(&format!("{} v2.0.0", "a".repeat(40))),
        }
    }

    #[test]
    fn a_rust_repository_holds_every_managed_file_under_the_header() {
        let files = managed_files(&repository(QualityConfig::default())).unwrap();
        let paths: Vec<&str> = files.iter().map(|(path, _)| path.as_str()).collect();
        assert_eq!(
            paths,
            [
                ".config/nextest.toml",
                ".editorconfig",
                ".gitattributes",
                ".github/dependabot.yml",
                ".github/workflows/ci.yml",
                ".pre-commit-config.yaml",
                ".rumdl.toml",
                ".taplo.toml",
                ".yamlfmt.yml",
                "Cargo.toml",
                "clippy.toml",
                "deny.toml",
                "rust-toolchain.toml",
                "rustfmt.toml",
                "typos.toml",
            ]
        );
        for (path, text) in files.iter().filter(|(path, _)| path != "Cargo.toml") {
            assert!(text.starts_with(HEADER), "{path} opens without the header");
        }
    }

    #[test]
    fn the_caller_pins_one_release_and_passes_the_declared_inputs() {
        let config = QualityConfig {
            ci: vec![("platforms".to_owned(), "macos windows".to_owned())],
            typos: vec!["jaq".to_owned()],
            ..QualityConfig::default()
        };
        let files = managed_files(&repository(config)).unwrap();
        let text = |wanted: &str| {
            files
                .iter()
                .find(|(path, _)| path == wanted)
                .map(|(_, text)| text.clone())
                .unwrap()
        };
        let caller = text(".github/workflows/ci.yml");
        let commit = "a".repeat(40);
        assert!(caller.contains(&format!(
            "    uses: Orchestration-Maestro/rust-workflows/.github/workflows/ci.yml@{commit}  \
             # v2.0.0\n    permissions:\n      contents: read\n    with:\n      platforms: \
             macos windows\n"
        )));
        assert_eq!(caller.matches(&commit).count(), 3);
        assert!(text("typos.toml").ends_with("[default.extend-words]\njaq = \"jaq\"\n"));
        let mut unpinned = repository(QualityConfig::default());
        unpinned.pin = None;
        assert!(
            managed_files(&unpinned)
                .unwrap_err()
                .starts_with("no release to pin")
        );
    }
}
