//! `rust-gate guide` and `guide --check`: a repository's Copilot guide,
//! written from its tracked files, keeping every explanation already given,
//! and refused when stale.

use crate::harness::{Fixture, refused, succeeds};
use std::fs;
use std::process::Output;

/// The guide every repository keeps.
const GUIDE: &str = ".github/copilot-instructions.md";

/// A small repository: a README with a title, a purpose, a table and an
/// image, a Rust module, a workflow, a ruleset and a note.
const FILES: [(&str, &str); 6] = [
    (
        "README.md",
        concat!(
            "# Example\n\nAn example repository for the guide. It has more.\n\n",
            "| Path | What it holds |\n| --- | --- |\n| `docs/` | Where the notes live |\n\n",
            "![The logo of the example]",
            "(assets/logo.png)\n",
        ),
    ),
    ("src/lib.rs", "//! The library: one function that adds.\n"),
    (
        ".github/workflows/ci.yml",
        concat!(
            "name: CI\non: push\njobs:\n  rust:\n    uses: ",
            "Orchestration-Maestro/rust-workflows/.github/workflows/ci.yml@abc\n",
        ),
    ),
    (
        "org/rules.json",
        "{\"name\": \"floor\", \"rules\": [{\"type\": \"update\"}, {\"type\": \"deletion\"}]}\n",
    ),
    ("assets/logo.png", "not really a picture\n"),
    (
        "docs/notes.md",
        "# Notes on the design\n\nWhy it is built this way.\n",
    ),
];

/// Run `command` in the fixture's project.
fn in_project(fixture: &Fixture, command: &str) -> Output {
    fixture.run_body(&format!("cd project && {command}"))
}

/// A fixture whose project is a git repository holding `FILES`.
fn repository() -> Fixture {
    let fixture = Fixture::new();
    for (path, text) in FILES {
        let file = fixture.root.join("project").join(path);
        fs::create_dir_all(file.parent().unwrap()).unwrap();
        fs::write(file, text).unwrap();
    }
    succeeds(&in_project(
        &fixture,
        "git init -q && git remote add origin \
         https://github.com/Orchestration-Maestro/example.git && git add -A",
    ));
    fixture
}

/// The fixture's guide.
fn guide(fixture: &Fixture) -> String {
    fs::read_to_string(fixture.root.join("project").join(GUIDE)).unwrap()
}

/// Whether the tree line of `name` in `guide` ends with the explanation `text`.
fn explains(guide: &str, name: &str, text: &str) -> bool {
    guide
        .lines()
        .any(|line| line.contains(&format!("── {name} ")) && line.ends_with(&format!("# {text}")))
}

#[test]
fn guide_writes_every_tracked_file_and_a_second_run_changes_nothing() {
    let fixture = repository();
    succeeds(&in_project(&fixture, "rust-gate guide"));
    let first = guide(&fixture);
    assert!(first.starts_with(
        "# Copilot instructions for Example\n\n## Start here\n\nAn example repository for the \
         guide. It has more.\n"
    ));
    for (name, text) in [
        ("lib.rs", "The library: one function that adds"),
        ("ci.yml", "CI: calls ci.yml"),
        ("rules.json", "Ruleset floor: deletion, update"),
        ("logo.png", "The logo of the example"),
        ("docs/", "Where the notes live"),
        ("notes.md", "Notes on the design"),
        ("README.md", "An example repository for the guide"),
        ("Cargo.toml", "Crate manifest"),
        ("workflows/", "GitHub Actions workflows"),
        (
            "copilot-instructions.md",
            "This guide, written by rust-gate guide at every commit",
        ),
    ] {
        assert!(explains(&first, name, text), "{name}: {text}\n{first}");
    }
    succeeds(&in_project(&fixture, "rust-gate guide"));
    assert_eq!(first, guide(&fixture));
}

#[test]
fn an_explanation_written_by_hand_survives_and_an_old_default_goes() {
    let fixture = repository();
    succeeds(&in_project(&fixture, "rust-gate guide"));
    let edited = guide(&fixture)
        .replace(
            "# The library: one function that adds",
            "# The adder, explained by hand",
        )
        .replace(
            "# This guide, written by rust-gate guide at every commit",
            "# This guide, regenerated by the organization's script",
        );
    fs::write(fixture.root.join("project").join(GUIDE), edited).unwrap();
    succeeds(&in_project(&fixture, "rust-gate guide"));
    let written = guide(&fixture);
    assert!(explains(&written, "lib.rs", "The adder, explained by hand"));
    assert!(explains(
        &written,
        "copilot-instructions.md",
        "This guide, written by rust-gate guide at every commit"
    ));
}

#[test]
fn the_check_refuses_a_guide_a_new_file_left_stale() {
    let fixture = repository();
    refused(
        &in_project(&fixture, "rust-gate guide --check"),
        "guide --check: .github/copilot-instructions.md is stale; run rust-gate guide and \
         commit it",
    );
    succeeds(&in_project(
        &fixture,
        "rust-gate guide && rust-gate guide --check",
    ));
    fs::write(
        fixture.root.join("project/src/extra.rs"),
        "//! One more module.\n",
    )
    .unwrap();
    succeeds(&in_project(&fixture, "git add -A"));
    refused(
        &in_project(&fixture, "rust-gate guide --check"),
        "is stale; run rust-gate guide and commit it",
    );
    succeeds(&in_project(&fixture, "rust-gate guide"));
    assert!(explains(&guide(&fixture), "extra.rs", "One more module"));
    succeeds(&in_project(&fixture, "rust-gate guide --check"));
}
