//! `rust-gate init`, `sync`, `sync --check` and the `managed-files` step of
//! `ci.yml`: the files every organization repository holds exactly as the
//! gate renders them, refused by name when they differ, and written back.

use crate::harness::{Fixture, refused, succeeds, tool};
use std::fs;
use std::process::Output;

/// The release the fixture's caller pins.
fn pin(letter: char, version: &str) -> String {
    format!(
        "RUST_WORKFLOWS_PIN='{} v{version}'",
        letter.to_string().repeat(40)
    )
}

/// Run `command` in the fixture's project, the repository root here.
fn in_project(fixture: &Fixture, command: &str) -> Output {
    fixture.run_body(&format!("cd project && {command}"))
}

/// A managed file of the fixture's project.
fn managed(fixture: &Fixture, path: &str) -> String {
    fs::read_to_string(fixture.root.join("project").join(path)).unwrap()
}

#[test]
fn init_writes_every_managed_file_and_the_check_finds_them_equal() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    refused(
        &in_project(&fixture, "rust-gate sync"),
        "no release to pin: .github/workflows/ci.yml names none; set RUST_WORKFLOWS_PIN to \
         `<commit> v<version>`",
    );
    refused(
        &in_project(&fixture, "rust-gate init"),
        "init: set RUST_WORKFLOWS_PIN to `<commit> v<version>`, the release to pin",
    );
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    for path in [
        ".config/nextest.toml",
        ".editorconfig",
        ".gitattributes",
        ".github/dependabot.yml",
        ".github/workflows/ci.yml",
        ".taplo.toml",
        ".yamlfmt.yml",
        "clippy.toml",
        "deny.toml",
        "rust-toolchain.toml",
        "rustfmt.toml",
        "typos.toml",
    ] {
        assert!(
            managed(&fixture, path).starts_with("# generated by rust-gate sync; do not edit\n"),
            "{path}"
        );
    }
    // TST-004: a flaky test fails the run instead of passing on a retry.
    assert!(
        managed(&fixture, ".config/nextest.toml").ends_with("[profile.default]\nretries = 0\n")
    );
    let caller = managed(&fixture, ".github/workflows/ci.yml");
    let commit = "a".repeat(40);
    assert!(caller.contains(&format!(
        "uses: Orchestration-Maestro/rust-workflows/.github/workflows/ci.yml@{commit}  # v2.0.0"
    )));
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    refused(
        &in_project(&fixture, &format!("{} rust-gate init", pin('a', "2.0.0"))),
        "init: the repository already has a caller; run rust-gate sync",
    );
    // What a repository's own hooks run over them leaves them as they are.
    let project = fixture.root.join("project");
    let yaml = tool("yamlfmt")
        .args([
            "-no_global_conf",
            "-lint",
            ".github/dependabot.yml",
            ".github/workflows/ci.yml",
        ])
        .current_dir(&project)
        .output()
        .unwrap();
    succeeds(&yaml);
    let toml = tool("taplo")
        .args(["fmt", "--check"])
        .current_dir(&project)
        .output()
        .unwrap();
    succeeds(&toml);
}

#[test]
fn a_managed_file_changed_by_hand_is_refused_and_sync_writes_it_back() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    fs::write(
        project.join("clippy.toml"),
        managed(&fixture, "clippy.toml").replace("= 100", "= 150"),
    )
    .unwrap();
    fs::remove_file(project.join("typos.toml")).unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 2 managed files differ from the organization's rendering (clippy.toml, \
         typos.toml); run rust-gate sync",
    );
    // Without a pin, sync keeps the release the caller pins; with one, it
    // moves every call to it.
    succeeds(&in_project(&fixture, "rust-gate sync"));
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    assert_eq!(
        managed(&fixture, ".github/workflows/ci.yml")
            .matches(&"a".repeat(40))
            .count(),
        3
    );
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate sync", pin('b', "2.1.0")),
    ));
    let caller = managed(&fixture, ".github/workflows/ci.yml");
    assert_eq!(caller.matches(&"b".repeat(40)).count(), 3);
    assert!(caller.contains("  # v2.1.0\n"));
    refused(
        &in_project(&fixture, "RUST_WORKFLOWS_PIN=v2 rust-gate sync"),
        "RUST_WORKFLOWS_PIN `v2` is not `<commit> v<version>`",
    );
    // What maestro-quality.toml says reaches the files it shapes.
    fs::write(
        project.join("maestro-quality.toml"),
        "[typos]\nwords = [\"jaq\"]\n\n[ci]\nplatforms = \"macos windows\"\ncoverage-threshold \
         = 95\n",
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 2 managed files differ from the organization's rendering \
         (.github/workflows/ci.yml, typos.toml); run rust-gate sync",
    );
    succeeds(&in_project(&fixture, "rust-gate sync"));
    assert!(managed(&fixture, "typos.toml").ends_with("jaq = \"jaq\"\n"));
    assert!(
        managed(&fixture, ".github/workflows/ci.yml")
            .contains("    with:\n      platforms: macos windows\n      coverage-threshold: 95\n")
    );
    fs::write(
        project.join("maestro-quality.toml"),
        "[typos]\nwords = [\"two words\"]\n",
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync"),
        "maestro-quality.toml: [typos] word `two words` is not one word",
    );
    fs::remove_file(project.join("maestro-quality.toml")).unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync"));
    // DEP-001: a duplicate version the ecosystem forces is excused in
    // maestro-quality.toml and becomes one of cargo-deny's skips.
    fs::write(
        project.join("maestro-quality.toml"),
        "[[exception]]\nrule = \"DEP-001\"\npath = \"windows-sys@0.52\"\nreason = \"two \
         platform crates pin it\"\n",
    )
    .unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync"));
    assert!(managed(&fixture, "deny.toml").ends_with(
        "multiple-versions = \"deny\"\nwildcards = \"deny\"\nskip = [\n  { crate = \
         \"windows-sys@0.52\", reason = \"two platform crates pin it\" },\n]\n"
    ));
    let toml = tool("taplo")
        .args(["fmt", "--check", "deny.toml"])
        .current_dir(&project)
        .output()
        .unwrap();
    succeeds(&toml);
    fs::remove_file(project.join("maestro-quality.toml")).unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync"));
    // The lint block of the root manifest is managed as well.
    let manifest = managed(&fixture, "Cargo.toml");
    fs::write(
        project.join("Cargo.toml"),
        manifest.replace("clippy.panic = \"deny\"\n", ""),
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 1 managed file differs from the organization's rendering (Cargo.toml); \
         run rust-gate sync",
    );
}

#[test]
fn the_managed_files_step_refuses_a_difference_in_ci() {
    let mut fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    fixture.set("GITHUB_WORKSPACE", &project.display().to_string());
    succeeds(&fixture.run("ci", "managed-files"));
    fs::write(project.join(".editorconfig"), "root = true\n").unwrap();
    refused(
        &fixture.run("ci", "managed-files"),
        "managed files: 1 managed file differs from the organization's rendering \
         (.editorconfig); run rust-gate sync",
    );
    assert_eq!(
        fs::read_to_string(fixture.root.join("reports/managed-files.txt")).unwrap(),
        ".editorconfig\n"
    );
}
