//! `rust-gate init`, `sync`, `sync --check` and the `managed-files` step of
//! `ci.yml`: the files every organization repository holds exactly as the
//! gate renders them, refused by name when they differ, and written back.

use crate::harness::{Fixture, refused, succeeds, tool};
use std::fs;
use std::process::Output;

/// The release the fixture's caller pins.
fn pin(letter: char, version: &str) -> String {
    format!(
        "RUST_WORKFLOWS_PIN='{} v{version}'",
        letter.to_string().repeat(40)
    )
}

/// The files sync wrote before the gate passed their tools the
/// organization's configuration at run time.
const RETIRED: [&str; 7] = [
    ".config/nextest.toml",
    ".rumdl.toml",
    ".taplo.toml",
    ".yamlfmt.yml",
    "clippy.toml",
    "deny.toml",
    "rustfmt.toml",
];

/// Run `command` in the fixture's project, the repository root here.
fn in_project(fixture: &Fixture, command: &str) -> Output {
    fixture.run_body(&format!("cd project && {command}"))
}

/// A managed file of the fixture's project.
fn managed(fixture: &Fixture, path: &str) -> String {
    fs::read_to_string(fixture.root.join("project").join(path)).unwrap()
}

#[test]
fn init_writes_every_managed_file_and_the_check_finds_them_equal() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    refused(
        &in_project(&fixture, "rust-gate sync"),
        "no release to pin: .github/workflows/ci.yml names none; set RUST_WORKFLOWS_PIN to \
         `<commit> v<version>`",
    );
    refused(
        &in_project(&fixture, "rust-gate init"),
        "init: set RUST_WORKFLOWS_PIN to `<commit> v<version>`, the release to pin",
    );
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    for path in [
        ".editorconfig",
        ".gitattributes",
        ".github/dependabot.yml",
        ".github/workflows/ci.yml",
        ".pre-commit-config.yaml",
        "rust-toolchain.toml",
        "typos.toml",
    ] {
        assert!(
            managed(&fixture, path).starts_with("# generated by rust-gate sync; do not edit\n"),
            "{path}"
        );
    }
    // Every other tool takes the organization's configuration at run time.
    for path in RETIRED {
        assert!(!fixture.root.join("project").join(path).exists(), "{path}");
    }
    let caller = managed(&fixture, ".github/workflows/ci.yml");
    let commit = "a".repeat(40);
    assert!(caller.contains(&format!(
        "uses: Orchestration-Maestro/rust-workflows/.github/workflows/ci.yml@{commit}  # v2.0.0"
    )));
    // Every Rust repository tests macOS and Windows, asked or not.
    assert!(caller.contains("    with:\n      platforms: macos windows\n"));
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    refused(
        &in_project(&fixture, &format!("{} rust-gate init", pin('a', "2.0.0"))),
        "init: the repository already has a caller; run rust-gate sync",
    );
    // What a repository's own hooks run over them leaves them as they are.
    let project = fixture.root.join("project");
    let yaml = tool("yamlfmt")
        .args([
            "-no_global_conf",
            "-lint",
            "-formatter",
            "indent=2,include_document_start=false,retain_line_breaks_single=true,\
             pad_line_comments=2,line_ending=lf",
            ".github/dependabot.yml",
            ".github/workflows/ci.yml",
        ])
        .current_dir(&project)
        .output()
        .unwrap();
    succeeds(&yaml);
    let toml = tool("taplo")
        .args([
            "fmt",
            "--check",
            "--no-auto-config",
            "--option",
            "array_auto_collapse=false",
        ])
        .current_dir(&project)
        .output()
        .unwrap();
    succeeds(&toml);
}

#[test]
fn a_managed_file_changed_by_hand_is_refused_and_sync_writes_it_back() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    // A file sync wrote before its tool took the organization's configuration
    // at run time is refused until sync deletes it; one the repository wrote
    // itself is not sync's to delete.
    fs::write(
        project.join("clippy.toml"),
        "# generated by rust-gate sync; do not edit\ntoo-many-lines-threshold = 100\n",
    )
    .unwrap();
    fs::write(project.join("rustfmt.toml"), "newline_style = \"Unix\"\n").unwrap();
    fs::remove_file(project.join("typos.toml")).unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 2 managed files differ from the organization's rendering (clippy.toml, \
         typos.toml); run rust-gate sync",
    );
    // Without a pin, sync keeps the release the caller pins; with one, it
    // moves every call to it.
    succeeds(&in_project(&fixture, "rust-gate sync"));
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    assert!(!project.join("clippy.toml").exists());
    assert!(project.join("rustfmt.toml").exists());
    assert_eq!(
        managed(&fixture, ".github/workflows/ci.yml")
            .matches(&"a".repeat(40))
            .count(),
        3
    );
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate sync", pin('b', "2.1.0")),
    ));
    let caller = managed(&fixture, ".github/workflows/ci.yml");
    assert_eq!(caller.matches(&"b".repeat(40)).count(), 3);
    assert!(caller.contains("  # v2.1.0\n"));
    refused(
        &in_project(&fixture, "RUST_WORKFLOWS_PIN=v2 rust-gate sync"),
        "RUST_WORKFLOWS_PIN `v2` is not `<commit> v<version>`",
    );
    // What maestro-quality.toml says reaches the files it shapes.
    fs::write(
        project.join("maestro-quality.toml"),
        "[typos]\nwords = [\"jaq\"]\n\n[ci]\nplatforms = \"macos windows\"\ncoverage-threshold \
         = 95\n",
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 2 managed files differ from the organization's rendering \
         (.github/workflows/ci.yml, typos.toml); run rust-gate sync",
    );
    succeeds(&in_project(&fixture, "rust-gate sync"));
    assert!(managed(&fixture, "typos.toml").ends_with("jaq = \"jaq\"\n"));
    assert!(
        managed(&fixture, ".github/workflows/ci.yml")
            .contains("    with:\n      platforms: macos windows\n      coverage-threshold: 95\n")
    );
    fs::write(
        project.join("maestro-quality.toml"),
        "[typos]\nwords = [\"two words\"]\n",
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync"),
        "maestro-quality.toml: [typos] word `two words` is not one word",
    );
    fs::remove_file(project.join("maestro-quality.toml")).unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync"));
    // The lint block of the root manifest is managed as well.
    let manifest = managed(&fixture, "Cargo.toml");
    fs::write(
        project.join("Cargo.toml"),
        manifest.replace("clippy.panic = \"deny\"\n", ""),
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 1 managed file differs from the organization's rendering (Cargo.toml); \
         run rust-gate sync",
    );
}

#[test]
fn platforms_that_drop_macos_or_windows_are_refused_with_the_fix() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    // A value may add a target, never drop macOS or Windows.
    fs::write(
        project.join("maestro-quality.toml"),
        "[ci]\nplatforms = \"linux-arm\"\n",
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync"),
        "maestro-quality.toml: [ci] platforms `linux-arm` drops macos and windows, which every \
         Rust repository tests: set it to `macos windows linux-arm`",
    );
    fs::write(
        project.join("maestro-quality.toml"),
        "[ci]\nplatforms = \"macos windows linux-arm\"\n",
    )
    .unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync"));
    assert!(
        managed(&fixture, ".github/workflows/ci.yml")
            .contains("    with:\n      platforms: macos windows linux-arm\n  #")
    );
}

#[test]
fn the_managed_files_step_refuses_a_difference_in_ci() {
    let mut fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    fixture.set("GITHUB_WORKSPACE", &project.display().to_string());
    succeeds(&fixture.run("ci", "managed-files"));
    fs::write(project.join(".editorconfig"), "root = true\n").unwrap();
    refused(
        &fixture.run("ci", "managed-files"),
        "managed files: 1 managed file differs from the organization's rendering \
         (.editorconfig); run rust-gate sync",
    );
    assert_eq!(
        fs::read_to_string(fixture.root.join("reports/managed-files.txt")).unwrap(),
        ".editorconfig\n"
    );
}

#[test]
fn markdown_settings_at_the_root_are_refused_and_a_subdirectory_keeps_its_own() {
    let mut fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    fixture.set("GITHUB_WORKSPACE", &project.display().to_string());
    // A subdirectory's settings apply to it alone: its fixtures may be exempt.
    fs::create_dir_all(project.join("examples")).unwrap();
    let everything = "[global]\ndisable = [\"all\"]\n";
    fs::write(project.join("examples/.rumdl.toml"), everything).unwrap();
    fs::write(project.join("pyproject.toml"), "[project]\nname = \"a\"\n").unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    // At the root, rumdl would read them for every file the hook checks.
    fs::write(project.join(".rumdl.toml"), everything).unwrap();
    fs::write(project.join(".markdownlint.yaml"), "default: false\n").unwrap();
    fs::write(
        project.join("pyproject.toml"),
        "[tool.rumdl]\ndisable = [\"all\"]\n",
    )
    .unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: .markdownlint.yaml, .rumdl.toml, pyproject.toml would loosen the \
         organization's Markdown settings at the root; a .rumdl.toml in a subdirectory \
         applies to it alone",
    );
    fs::remove_file(project.join(".markdownlint.yaml")).unwrap();
    fs::remove_file(project.join("pyproject.toml")).unwrap();
    refused(
        &fixture.run("ci", "managed-files"),
        "managed files: .rumdl.toml would loosen the organization's Markdown settings at \
         the root; a .rumdl.toml in a subdirectory applies to it alone",
    );
}

#[test]
fn the_home_may_change_the_files_it_is_the_source_of() {
    let mut fixture = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &fixture,
        &format!("{} rust-gate init", pin('a', "2.0.0")),
    ));
    let project = fixture.root.join("project");
    fixture.set("GITHUB_WORKSPACE", &project.display().to_string());
    let edited = format!("{}*.snap binary\n", managed(&fixture, ".gitattributes"));
    fs::write(project.join(".gitattributes"), &edited).unwrap();
    refused(
        &fixture.run("ci", "managed-files"),
        "managed files: 1 managed file differs from the organization's rendering \
         (.gitattributes); run rust-gate sync",
    );
    // The home of the workflows: its ci.yml is called, not a caller.
    fs::write(
        project.join(".github/workflows/ci.yml"),
        "name: CI\non:\n  workflow_call:\n",
    )
    .unwrap();
    succeeds(&fixture.run("ci", "managed-files"));
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    succeeds(&in_project(&fixture, "rust-gate sync"));
    assert_eq!(managed(&fixture, ".gitattributes"), edited);
    // The home keeps copies of its own, without the header, for its own tools.
    fs::write(
        project.join("clippy.toml"),
        "too-many-lines-threshold = 100\n",
    )
    .unwrap();
    fs::write(
        project.join(".rumdl.toml"),
        "[global]\ndisable = [\"MD013\"]\n",
    )
    .unwrap();
    succeeds(&in_project(&fixture, "rust-gate sync --check"));
    // What the gate writes from its data is still the organization's.
    fs::write(project.join("typos.toml"), "[default]\n").unwrap();
    refused(
        &in_project(&fixture, "rust-gate sync --check"),
        "sync --check: 1 managed file differs from the organization's rendering \
         (typos.toml); run rust-gate sync",
    );
}

#[test]
fn init_writes_the_rule_map_and_in_a_git_repository_the_guide() {
    let outside = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    let written = in_project(&outside, &format!("{} rust-gate init", pin('a', "2.0.0")));
    succeeds(&written);
    assert!(
        managed(&outside, "docs/standards/engineering.md").starts_with("# Engineering rules in `")
    );
    assert!(
        !outside
            .root
            .join("project/.github/copilot-instructions.md")
            .exists()
    );
    assert!(String::from_utf8_lossy(&written.stdout).contains("the first commit's hook writes it"));
    let inside = Fixture::with_sources(&[("src/lib.rs", "//! A crate.\n")]);
    succeeds(&in_project(
        &inside,
        &format!(
            "git init -q && git remote add origin \
             https://github.com/Orchestration-Maestro/example.git && git add -A && {} rust-gate \
             init",
            pin('a', "2.0.0")
        ),
    ));
    assert!(
        managed(&inside, "docs/standards/security.md").starts_with("# Security rules in `example`")
    );
    assert!(managed(&inside, ".github/copilot-instructions.md").contains("── lib.rs"));
}
