//! `ci.yml` and `rust-gate lints --write`: LNT-001, the organization's lints
//! denied in the root manifest, written by the gate and refused when missing;
//! its thresholds, handed to Clippy at run time, and a `clippy.toml` a
//! repository commits refused when looser; all of it read by Clippy itself.

use crate::harness::{Fixture, refused, root, succeeds};
use std::fs;
use std::process::Output;

/// A library every organization lint passes.
const CLEAN: &str = "//! Sums.\n\n/// The sum, saturated.\n#[must_use]\npub fn sum(left: u32, \
                     right: u32) -> u32 {\n    left.saturating_add(right)\n}\n";

/// The report the architecture step wrote.
fn report(fixture: &Fixture) -> String {
    fs::read_to_string(fixture.root.join("reports/architecture.txt")).unwrap()
}

/// Real Clippy over the fixture's project, run the way the pre-push hook
/// runs it: through the gate, which hands Clippy the organization's
/// thresholds.
fn clippy(fixture: &Fixture) -> Output {
    fixture.run_body(&format!(
        "cd project && cargo generate-lockfile --offline && CARGO_TARGET_DIR={} rust-gate \
         clippy --local",
        fixture.root.join("target").display()
    ))
}

#[test]
fn a_manifest_without_the_organization_lints_is_refused_until_written() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", CLEAN)]);
    let manifest = fixture.root.join("project/Cargo.toml");
    let plain = "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n\
                 publish = false\n";
    fs::write(&manifest, plain).unwrap();
    refused(
        &fixture.run("ci", "architecture"),
        "source rules: 1 finding",
    );
    assert!(
        report(&fixture).starts_with(
            "LNT-001 project/Cargo.toml: 34 of the organization's lints are not denied \
             (clippy::all, clippy::pedantic, clippy::cargo, rust::rust_2018_idioms, \
             rust::nonstandard_style, clippy::allow_attributes,"
        ),
        "{}",
        report(&fixture)
    );
    assert!(report(&fixture).contains("); write them with rust-gate lints --write\n"));
    succeeds(&fixture.run_body("cd project && rust-gate lints --write"));
    succeeds(&fixture.run("ci", "architecture"));
    // Written twice, the block replaces itself, and a lint the repository
    // adds below it stays.
    fs::write(
        &manifest,
        fs::read_to_string(&manifest).unwrap() + "clippy.own = \"deny\"\n",
    )
    .unwrap();
    let once = fs::read_to_string(&manifest).unwrap();
    succeeds(&fixture.run_body("cd project && rust-gate lints --write"));
    assert_eq!(fs::read_to_string(&manifest).unwrap(), once);
    // A table of its own beside the block would be one table twice.
    fs::write(
        &manifest,
        format!("{plain}[lints.clippy]\npanic = \"deny\"\n"),
    )
    .unwrap();
    refused(
        &fixture.run_body("cd project && rust-gate lints --write"),
        "lints --write: Cargo.toml: the manifest already sets lints in `[lints.clippy]`; remove \
         that table, run this again, then add the lints the organization does not hold below \
         the generated block",
    );
    refused(
        &fixture.run_body("rust-gate lints --write"),
        "; run it where the root manifest is",
    );
    fs::write(
        &manifest,
        format!(
            "{plain}# generated by rust-gate lints --write; do not edit down to the end marker\n"
        ),
    )
    .unwrap();
    refused(
        &fixture.run_body("cd project && rust-gate lints --write"),
        "lints --write: Cargo.toml: the generated lints open with their marker and never close",
    );
}

#[test]
fn a_clippy_toml_looser_than_the_organization_s_is_refused() {
    let fixture = Fixture::with_sources(&[("src/lib.rs", CLEAN)]);
    let config = fixture.root.join("clippy.toml");
    // Without one, the gate hands Clippy the organization's own.
    succeeds(&fixture.run("ci", "architecture"));
    let organization = fs::read_to_string(root().join("clippy.toml")).unwrap();
    fs::write(&config, &organization).unwrap();
    succeeds(&fixture.run("ci", "architecture"));
    // Tighter is the repository's call.
    fs::write(
        &config,
        organization.replace(
            "too-many-lines-threshold = 100",
            "too-many-lines-threshold = 80",
        ),
    )
    .unwrap();
    succeeds(&fixture.run("ci", "architecture"));
    let looser = organization
        .replace(
            "too-many-lines-threshold = 100",
            "too-many-lines-threshold = 150",
        )
        .replace("allow-dbg-in-tests = false\n", "");
    fs::write(&config, looser).unwrap();
    refused(
        &fixture.run("ci", "architecture"),
        "source rules: 2 findings",
    );
    assert_eq!(
        report(&fixture),
        "LNT-001 clippy.toml: `allow-dbg-in-tests` is not set; the organization sets false\n\
         LNT-001 clippy.toml: `too-many-lines-threshold` is 150, looser than the organization's \
         100\n"
    );
}

#[test]
fn clippy_knows_every_organization_lint_and_applies_it() {
    // Real Clippy on the written block and the organization's clippy.toml the
    // gate hands it: a lint or a key Clippy does not know fails this run, a
    // denied lint fails code that breaks it, and a function over the
    // organization's 100 lines is refused with no clippy.toml committed.
    let fixture = Fixture::with_sources(&[("src/lib.rs", CLEAN)]);
    succeeds(&clippy(&fixture));
    let unwrapping = CLEAN.replace(
        "left.saturating_add(right)",
        "left.checked_add(right).unwrap()",
    );
    fs::write(fixture.root.join("project/src/lib.rs"), unwrapping).unwrap();
    let output = clippy(&fixture);
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("used `unwrap()` on an `Option` value"),
        "{stderr}"
    );
    let long = format!(
        "{CLEAN}\n/// Counts.\n#[must_use]\npub fn count() -> u32 {{\n    let mut total = 0;\n\
         {}    total\n}}\n",
        "    total += 1;\n".repeat(100)
    );
    fs::write(fixture.root.join("project/src/lib.rs"), long).unwrap();
    let output = clippy(&fixture);
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("this function has too many lines (") && stderr.contains("/100)"),
        "{stderr}"
    );
    assert!(!fixture.root.join("clippy.toml").exists());
}
