//! `ci.yml`: the dependency policy, direct crates.io access and the scanners.

use crate::harness::{Fixture, refused, succeeds};
use std::fs;
use std::path::Path;

#[test]
fn the_organization_dependency_policy_applies_to_every_repository() {
    // DEP-001 for every project, rendered by the gate at run time with the
    // duplicate versions maestro-quality.toml excuses: no deny.toml is copied
    // into the repository, and the report says which policy applied.
    let record = r#"[[ "$1" == deny ]] || exit 0"#;
    let mut absent = Fixture::new();
    absent.set("DENY_CONFIG", "");
    absent.stub("cargo", record);
    fs::write(
        absent.root.join("maestro-quality.toml"),
        "[[exception]]\nrule = \"DEP-001\"\npath = \"windows-sys@0.52\"\nreason = \"two \
         platform crates pin it\"\n",
    )
    .unwrap();
    succeeds(&absent.run("ci", "licenses"));
    let report = fs::read_to_string(absent.root.join("reports/licenses.txt")).unwrap();
    assert!(
        report.starts_with("policy: the organization's DEP-001, rendered by the gate"),
        "{report}"
    );
    let config = fs::read_to_string(absent.root.join("organization-deny.toml")).unwrap();
    for line in [
        "  \"Unicode-3.0\",\n",
        "yanked = \"deny\"\n",
        "unknown-git = \"deny\"\n",
        "multiple-versions = \"deny\"\n",
    ] {
        assert!(config.contains(line), "{line}: {config}");
    }
    assert!(config.ends_with(
        "wildcards = \"deny\"\nskip = [\n  { crate = \"windows-sys@0.52\", reason = \"two \
         platform crates pin it\" },\n]\n"
    ));
    // RUNNER_TEMP carries a trailing slash in the fixture, so match the file
    // name and the check list rather than the exact path string.
    assert!(
        absent
            .calls()
            .contains("/organization-deny.toml check licenses bans sources advisories\n"),
        "calls:\n{}",
        absent.calls()
    );

    // The tool's failure is the gate.
    let mut enforced = Fixture::new();
    enforced.set("DENY_CONFIG", "");
    enforced.stub(
        "cargo",
        r#"[[ "$1" == deny ]] || exit 0
echo "checking"; exit 1"#,
    );
    assert!(
        !enforced.run("ci", "licenses").status.success(),
        "a policy that fails must fail the job"
    );
}

#[test]
fn the_organization_allowlist_adds_licences_and_a_committed_policy_is_refused() {
    // The organization list adds licences to DEP-001's; a deny.toml the
    // repository wrote itself is refused, one rust-gate sync wrote is left to
    // sync to delete, and a malformed list is refused before cargo-deny runs.
    let record = r#"[[ "$1" == deny ]] || exit 0"#;
    let mut org = Fixture::new();
    org.set("DENY_CONFIG", "");
    org.set("LICENSE_ALLOWLIST", "MIT,ISC");
    org.stub("cargo", record);
    succeeds(&org.run("ci", "licenses"));
    let config = fs::read_to_string(org.root.join("organization-deny.toml")).unwrap();
    assert!(
        config.contains("  \"Unlicense\",\n  \"ISC\",\n]\n"),
        "{config}"
    );
    assert_eq!(config.matches("\"MIT\"").count(), 1, "{config}");
    assert!(
        fs::read_to_string(org.root.join("reports/licenses.txt"))
            .unwrap()
            .contains("organization licence allowlist: MIT,ISC")
    );

    let mut own = Fixture::new();
    own.set("DENY_CONFIG", "/somewhere/deny.toml");
    own.stub("cargo", record);
    refused(
        &own.run("ci", "licenses"),
        "deny.toml: the organization's DEP-001 policy applies to every repository; delete \
         deny.toml and take exceptions in maestro-quality.toml",
    );
    assert!(own.calls().is_empty());

    let mut synced = Fixture::new();
    let copy = synced.root.join("project/deny.toml");
    fs::write(
        &copy,
        "# generated by rust-gate sync; do not edit\n[bans]\nmultiple-versions = \"allow\"\n",
    )
    .unwrap();
    synced.set("DENY_CONFIG", &copy.display().to_string());
    synced.stub("cargo", record);
    succeeds(&synced.run("ci", "licenses"));
    assert!(
        synced
            .calls()
            .contains("/organization-deny.toml check licenses bans sources advisories\n")
    );

    let mut bad = Fixture::new();
    bad.set("DENY_CONFIG", "");
    bad.set("LICENSE_ALLOWLIST", "MIT; GPL-3.0");
    bad.stub("cargo", record);
    refused(
        &bad.run("ci", "licenses"),
        "LICENSE_ALLOWLIST must be comma-separated SPDX identifiers",
    );
    assert!(bad.calls().is_empty());
}

#[test]
fn ci_configures_direct_crates_io_without_writing_credentials() {
    let mut fixture = Fixture::new();
    fixture.set("CARGO_REGISTRY_TOKEN", "synthetic-unused-token");
    let output = fixture.run("ci", "registry");
    succeeds(&output);
    let environment = fs::read_to_string(fixture.root.join("environment")).unwrap();
    let home = environment
        .lines()
        .find_map(|line| line.strip_prefix("CARGO_HOME="))
        .expect("CARGO_HOME exported");
    assert!(Path::new(home).starts_with(&fixture.root));
    let config = fs::read_to_string(Path::new(home).join("config.toml")).unwrap();
    assert_eq!(config, "[registries.crates-io]\nprotocol = \"sparse\"\n");
    assert!(environment.contains("CARGO_REGISTRIES_CRATES_IO_PROTOCOL=sparse\n"));
    assert!(
        environment.contains("CARGO_REGISTRIES_CRATES_IO_INDEX=sparse+https://index.crates.io/\n")
    );
    assert!(!Path::new(home).join("credentials.toml").exists());
    let stdout = String::from_utf8_lossy(&output.stdout);
    for written in [environment.as_str(), config.as_str(), stdout.as_ref()] {
        assert!(!written.contains("synthetic-unused-token"));
    }
}

#[test]
fn scanners_propagate_findings_execution_errors_and_missing_tools() {
    let fixture = Fixture::new();
    fixture.stub("git", "tar -cf - --files-from /dev/null");
    for (command, id) in [("cargo", "audit"), ("gitleaks", "secrets")] {
        for status in [1, 2, 127] {
            fixture.stub(command, &format!("exit {status}"));
            assert_eq!(fixture.run("ci", id).status.code(), Some(status));
            assert!(fixture.calls().contains(command));
        }
        fixture.stub(command, "exit 0");
        assert!(
            !fixture.run("ci", id).status.success(),
            "Missing scanner report must fail"
        );
    }
}

#[test]
fn the_toolchain_step_installs_the_exact_pin_with_the_gate_components() {
    let fixture = Fixture::new();
    fixture.stub("rustup", "");
    succeeds(&fixture.run("ci", "tools"));
    let trace = fixture.trace();
    assert!(
        trace.contains(
            "rustup toolchain install 1.98.1 --profile minimal \
             --component rustfmt,clippy,llvm-tools-preview"
        ),
        "{trace}"
    );
    assert!(fixture.root.join("reports").is_dir());
    fixture.stub("rustup", "exit 3");
    assert_eq!(fixture.run("ci", "tools").status.code(), Some(3));
}
