//! The guide as a whole: where to start, the annotated tree, and how to
//! change and verify, for the repository at a root.

use super::text::{blocks, is_prose, title_of, wrap};
use super::tree::{kept, readme_rows, tree_lines};
use std::fs;
use std::path::Path;

/// Where every repository keeps its guide.
pub(super) const GUIDE: &str = ".github/copilot-instructions.md";

/// Where the organization publishes its default community files.
const ORG: &str = "https://github.com/Orchestration-Maestro/.github/blob/main";

/// Explanations the organization gave before, which a guide may still hold:
/// such an explanation is the organization's word, not the repository's,
/// and gives way to the current one.
const SUPERSEDED: [&str; 1] = ["This guide, regenerated by the organization's script"];

/// The guide for the repository at `root`, whose tracked files are `paths`,
/// sorted, and whose `origin` remote is `remote`, empty when it has none.
pub(super) fn render(root: &Path, paths: &[String], remote: &str) -> String {
    let current = fs::read_to_string(root.join(GUIDE)).unwrap_or_default();
    let mut previous = kept(&current);
    previous.retain(|_, text| !SUPERSEDED.contains(&text.as_str()));
    let name = readme_title(root).unwrap_or_else(|| repository_name(root, remote));
    let purpose = purpose(root).unwrap_or_else(|| format!("The {name} repository."));
    let mut lines = vec![
        format!("# Copilot instructions for {name}"),
        String::new(),
        "## Start here".to_owned(),
        String::new(),
        wrap(&purpose, ""),
        String::new(),
        wrap(&reading(root), ""),
        String::new(),
    ];
    if let Some(rules) = rules(root) {
        lines.extend([wrap(&rules, ""), String::new()]);
    }
    lines.extend([
        wrap(
            "Keep changes scoped to the request, and read historical plans and specifications \
             as records, not as instructions to start new work.",
            "",
        ),
        String::new(),
        "## Repository tree".to_owned(),
        String::new(),
        wrap(
            "Every tracked file, with what it is for. `rust-gate guide` writes this tree at \
             every commit and keeps each explanation already here, so improve an explanation \
             in place.",
            "",
        ),
        String::new(),
        "```text".to_owned(),
    ]);
    lines.extend(tree_lines(
        root,
        paths,
        &previous,
        &readme_rows(root, paths),
    ));
    lines.extend([
        "```".to_owned(),
        String::new(),
        "## Change and verification procedure".to_owned(),
        String::new(),
    ]);
    for (index, step) in steps(root).iter().enumerate() {
        lines.push(wrap(&format!("{}. {step}", index + 1), "   "));
    }
    lines.push(String::new());
    lines.join("\n")
}

/// A Markdown link to `target`, labelled `label`.
fn link(label: &str, target: &str) -> String {
    let mut text = format!("[{label}]");
    text.push('(');
    text.push_str(target);
    text.push(')');
    text
}

/// What to read before editing, and what binds every change.
fn reading(root: &Path) -> String {
    let mut reads = vec![format!(
        "{} for the rules that bind every change",
        link("AGENTS.md", "../AGENTS.md")
    )];
    if root.join("CONTEXT.md").is_file() {
        reads.push(format!(
            "{} for the words it uses",
            link("CONTEXT.md", "../CONTEXT.md")
        ));
    }
    reads.push(format!(
        "{} for how a change is proposed",
        link("CONTRIBUTING.md", &community(root, "CONTRIBUTING.md"))
    ));
    let (last, first) = reads
        .split_last()
        .map_or(("", &[][..]), |(last, first)| (last.as_str(), first));
    format!(
        "Paths below are relative to this repository. Before editing, read {} and {last}. The \
         organization's {} binds every specification, plan, review and release.",
        first.join(", "),
        link("constitution", &format!("{ORG}/CONSTITUTION.md"))
    )
}

/// Where the repository's rule map lives, when it has one.
fn rules(root: &Path) -> Option<String> {
    let standards: Vec<String> = ["northstar.md", "engineering.md", "security.md"]
        .iter()
        .filter(|page| root.join("docs/standards").join(page).is_file())
        .map(|page| link(page, &format!("../docs/standards/{page}")))
        .collect();
    let (last, first) = standards.split_last()?;
    let listed = if first.is_empty() {
        last.clone()
    } else {
        format!("{} and {last}", first.join(", "))
    };
    Some(format!(
        "For quality, engineering or security changes, read {listed}: this repository's map of \
         the organization's golden rules."
    ))
}

/// The five steps of the change and verification procedure.
fn steps(root: &Path) -> [String; 5] {
    [
        "Read the rules in AGENTS.md that cover the files you change, and keep every gate \
         intact: never weaken one to pass."
            .to_owned(),
        "Add an executable regression check for a change in behaviour.".to_owned(),
        "The commit hook `rust-gate guide` rewrites this guide when a file is added, moved or \
         removed; commit it with the change. The organization's daily drift check reports a \
         guide left stale."
            .to_owned(),
        format!(
            "Run {}, and report the commands you actually ran.",
            gate(root)
        ),
        "Commits are signed, with a conventional title; the default branch takes only \
         squash-merged pull requests."
            .to_owned(),
    ]
}

/// The link to the repository's own community file `name`, else to the
/// organization's default.
fn community(root: &Path, name: &str) -> String {
    ["", ".github/", "docs/"]
        .iter()
        .find(|place| root.join(format!("{place}{name}")).is_file())
        .map_or_else(
            || format!("{ORG}/{name}"),
            |place| format!("../{place}{name}"),
        )
}

/// The command that runs the repository's checks before a commit.
fn gate(root: &Path) -> &'static str {
    let justfile = fs::read_to_string(root.join("justfile")).unwrap_or_default();
    let check = justfile.lines().any(|line| {
        line.strip_prefix("check").is_some_and(|rest| {
            !rest.starts_with(|character: char| character.is_alphanumeric() || character == '_')
        })
    });
    match (check, root.join("scripts/bootstrap.sh").is_file()) {
        (false, _) => "`prek run --all-files`",
        (true, true) => "`scripts/bootstrap.sh` once, then `just check`",
        (true, false) => "`just check`",
    }
}

/// The README's Markdown title, never a `#` line inside a fenced block.
fn readme_title(root: &Path) -> Option<String> {
    let text = fs::read_to_string(root.join("README.md")).ok()?;
    title_of(&without_fences(&text)).map(str::to_owned)
}

/// `text` without its fenced blocks: from three backticks that open a line
/// to the three backticks that open a later one.
fn without_fences(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut from = 0;
    while let Some(open) = fence(text, from) {
        let Some(close) = fence(text, open + 3) else {
            break;
        };
        out.push_str(text.get(from..open).unwrap_or_default());
        from = close + 3;
    }
    out.push_str(text.get(from..).unwrap_or_default());
    out
}

/// The first three backticks, at or after `from`, that open a line of `text`.
fn fence(text: &str, from: usize) -> Option<usize> {
    text.match_indices("```")
        .map(|(at, _)| at)
        .find(|at| *at >= from && (*at == 0 || text.as_bytes().get(at - 1) == Some(&b'\n')))
}

/// The repository's name: the last part of its remote, else its folder's.
fn repository_name(root: &Path, remote: &str) -> String {
    let url = remote.trim().trim_end_matches('/');
    let last = url.rsplit(['/', ':']).next().unwrap_or_default();
    let last = last.strip_suffix(".git").unwrap_or(last);
    if !last.is_empty() {
        return last.to_owned();
    }
    fs::canonicalize(root)
        .ok()
        .and_then(|path| {
            path.file_name()
                .map(|name| name.to_string_lossy().into_owned())
        })
        .unwrap_or_default()
}

/// What the repository is: its README's first prose paragraph, whole, on one
/// line, its relative links made to resolve from the guide's directory.
fn purpose(root: &Path) -> Option<String> {
    let text = fs::read_to_string(root.join("README.md")).ok()?;
    let block = blocks(&without_first_heading(&text))
        .into_iter()
        .find(|block| is_prose(block))?;
    Some(
        relinked(&block)
            .split('\n')
            .map(str::trim)
            .collect::<Vec<_>>()
            .join(" "),
    )
}

/// `text` with its first line that opens with `#` emptied.
fn without_first_heading(text: &str) -> String {
    let mut emptied = false;
    text.split('\n')
        .map(|line| {
            if !emptied && line.starts_with('#') {
                emptied = true;
                ""
            } else {
                line
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

/// Where a Markdown link's target opens: its label's closing bracket and
/// the target's opening parenthesis.
const TARGET: &str = concat!("]", "(");

/// `text` with each relative Markdown link target prefixed with `../`, read
/// once from the left.
fn relinked(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 16);
    let mut rest = text;
    while let Some(at) = rest.find(TARGET) {
        let (before, from) = rest.split_at_checked(at + 2).unwrap_or((rest, ""));
        out.push_str(before);
        rest = from;
        let Some(end) = from.find(')').filter(|end| *end > 0) else {
            continue;
        };
        if is_absolute(from) {
            continue;
        }
        let (target, after) = from.split_at_checked(end + 1).unwrap_or((from, ""));
        out.push_str("../");
        out.push_str(target);
        rest = after;
    }
    out.push_str(rest);
    out
}

/// Whether a link target is absolute: rooted, an anchor, or with a scheme.
fn is_absolute(target: &str) -> bool {
    if target.starts_with(['/', '#']) {
        return true;
    }
    let mut characters = target.chars();
    let scheme_starts = characters
        .next()
        .is_some_and(|first| first.is_ascii_lowercase());
    let rest = characters.find(|character| {
        !(character.is_ascii_lowercase() || matches!(character, '+' | '.' | '-'))
    });
    scheme_starts && rest == Some(':')
}

#[cfg(test)]
mod tests {
    use super::{is_absolute, relinked, repository_name, without_fences, without_first_heading};
    use std::path::Path;

    #[test]
    fn fenced_blocks_and_the_first_heading_are_dropped() {
        let text = "Intro\n```\n# not a title\n```\n# Title\n";
        assert_eq!(without_fences(text), "Intro\n\n# Title\n");
        assert_eq!(without_fences("no ``` fence here\n"), "no ``` fence here\n");
        assert_eq!(without_first_heading("# A\ntext\n# B\n"), "\ntext\n# B\n");
    }

    #[test]
    fn relative_links_are_made_to_resolve_from_the_guide() {
        let text = concat!(
            "See [docs]",
            "(docs/a.md), [site]",
            "(https://x.y), [top]",
            "(#top) and ",
            "[root]",
            "(/r)."
        );
        let expected = concat!(
            "See [docs]",
            "(../docs/a.md), [site]",
            "(https://x.y), [top]",
            "(#top) and ",
            "[root]",
            "(/r)."
        );
        assert_eq!(relinked(text), expected);
        assert!(is_absolute("mailto:x") && is_absolute("git+ssh:x") && !is_absolute("a.md"));
    }

    #[test]
    fn the_repository_name_comes_from_its_remote() {
        let root = Path::new("/nowhere");
        assert_eq!(
            repository_name(
                root,
                "git@github.com:Orchestration-Maestro/maestro-core.git\n"
            ),
            "maestro-core"
        );
        assert_eq!(repository_name(root, "https://h/o/.github/"), ".github");
    }
}
