//! The text helpers of the guide: the first sentence of some prose, a
//! paragraph wrapped the way Python's `textwrap` wraps one, the blocks
//! between blank lines, a file's first comment, and the value of a `key:`
//! line.

/// The most characters an explanation keeps.
const LONGEST: usize = 140;

/// The column a paragraph wraps at.
const WIDTH: usize = 80;

/// The columns between two tab stops, as Python expands tabs.
const TAB: usize = 8;

/// What a block that is not prose opens with: a heading, a table, a fence, a
/// tag, an image, a list or a quotation.
pub(super) const NOT_PROSE: [&str; 9] = ["#", "|", "```", "<", "![", "[![", "- ", "* ", ">"];

/// The marker every file `rust-gate sync` writes carries.
pub(super) const MANAGED: &str = "generated by rust-gate";

/// The first sentence of `text` on one line: its links reduced to their
/// labels, its code and bold marks dropped, cut to `LONGEST` characters at a
/// clause or a word, without trailing punctuation.
pub(super) fn sentence(text: &str) -> String {
    let plain = unmarked(&unlinked(text));
    let joined = plain.split_whitespace().collect::<Vec<_>>().join(" ");
    shortened(first_sentence(&joined))
        .trim_end_matches(['.', ',', ';', ':', ' '])
        .to_owned()
}

/// `text` with every Markdown link reduced to its label, read once from the
/// left the way a regular expression reads it.
fn unlinked(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(open) = rest.find('[') {
        let (before, from) = rest.split_at_checked(open).unwrap_or((rest, ""));
        out.push_str(before);
        if let Some((label, spanned)) = link_label(from) {
            out.push_str(label);
            rest = from.get(spanned..).unwrap_or_default();
        } else {
            out.push('[');
            rest = from.get(1..).unwrap_or_default();
        }
    }
    out.push_str(rest);
    out
}

/// The label of the link `text` opens with, a bracketed label right before a
/// parenthesized target, and how many bytes the link spans.
fn link_label(text: &str) -> Option<(&str, usize)> {
    let close = text.find(']')?;
    let label = text.get(1..close)?;
    let target = text.get(close + 1..)?.strip_prefix('(')?;
    let end = target.find(')')?;
    (!label.is_empty()).then_some((label, close + 2 + end + 1))
}

/// `text` without code marks and bold marks, read once from the left.
fn unmarked(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(character) = rest.chars().next() {
        if let Some(after) = rest.strip_prefix("**") {
            rest = after;
            continue;
        }
        rest = rest.get(character.len_utf8()..).unwrap_or_default();
        if character != '`' {
            out.push(character);
        }
    }
    out
}

/// `text` up to its first sentence end: a full stop, an exclamation or a
/// question mark followed by a space.
fn first_sentence(text: &str) -> &str {
    text.match_indices(' ')
        .map(|(at, _)| at)
        .find(|at| {
            text.get(..*at)
                .is_some_and(|head| head.ends_with(['.', '!', '?']))
        })
        .and_then(|at| text.get(..at))
        .unwrap_or(text)
        .trim()
}

/// `text` cut to `LONGEST` characters: at its last clause when that keeps
/// more than half of them, else at its last word.
fn shortened(text: &str) -> &str {
    let Some((limit, _)) = text.char_indices().nth(LONGEST) else {
        return text;
    };
    let cut = text.get(..limit).unwrap_or(text);
    let clause = [", ", "; ", ": "]
        .iter()
        .filter_map(|mark| cut.rfind(mark))
        .max();
    match clause {
        Some(at) if cut.get(..at).map_or(0, |head| head.chars().count()) > LONGEST / 2 => {
            cut.get(..at).unwrap_or(cut)
        }
        _ => cut.rsplit_once(' ').map_or(cut, |(head, _)| head),
    }
}

/// A paragraph wrapped at `WIDTH` columns the way Python's `textwrap.fill`
/// wraps it, never breaking a hyphen or a long word: tabs expand, each
/// whitespace character counts as a space, runs of them stay inside a line
/// and go where a line breaks, and every line after the first opens with
/// `indent`.
pub(super) fn wrap(text: &str, indent: &str) -> String {
    let mut chunks = chunks(&expanded(text));
    chunks.reverse();
    let mut lines: Vec<String> = Vec::new();
    while !chunks.is_empty() {
        let prefix = if lines.is_empty() { "" } else { indent };
        if !lines.is_empty() && chunks.last().is_some_and(|chunk| chunk.trim().is_empty()) {
            chunks.pop();
        }
        let line = filled(&mut chunks, WIDTH.saturating_sub(prefix.chars().count()));
        if !line.is_empty() {
            lines.push(format!("{prefix}{line}"));
        }
    }
    lines.join("\n")
}

/// `text` with each tab expanded to the next tab stop, counted from the
/// start of its line.
fn expanded(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut column = 0;
    for character in text.chars() {
        if character == '\t' {
            let spaces = TAB - column % TAB;
            out.push_str(&" ".repeat(spaces));
            column += spaces;
        } else {
            out.push(character);
            column = if matches!(character, '\n' | '\r') {
                0
            } else {
                column + 1
            };
        }
    }
    out
}

/// `text` cut into alternating runs of words and of whitespace, each
/// whitespace character, as Python's `textwrap` counts them, a space.
fn chunks(text: &str) -> Vec<String> {
    let mut found: Vec<String> = Vec::new();
    for character in text.chars() {
        let space = matches!(character, '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ');
        let written = if space { ' ' } else { character };
        match found.last_mut() {
            Some(chunk) if chunk.starts_with(' ') == space => chunk.push(written),
            _ => found.push(written.to_string()),
        }
    }
    found
}

/// One line taken from the reversed `chunks`: what fits in `width`, a word
/// longer than the width alone on an otherwise empty line, and no
/// whitespace at its end.
fn filled(chunks: &mut Vec<String>, width: usize) -> String {
    let mut line: Vec<String> = Vec::new();
    let mut length = 0;
    while let Some(size) = chunks.last().map(|chunk| chunk.chars().count()) {
        if length + size > width {
            break;
        }
        length += size;
        line.extend(chunks.pop());
    }
    if line.is_empty()
        && chunks
            .last()
            .is_some_and(|chunk| chunk.chars().count() > width)
    {
        line.extend(chunks.pop());
    }
    if line.last().is_some_and(|chunk| chunk.trim().is_empty()) {
        line.pop();
    }
    line.concat()
}

/// The blocks of `text` between blank lines, each trimmed, empty ones left
/// out.
pub(super) fn blocks(text: &str) -> Vec<String> {
    let mut found = Vec::new();
    let mut block: Vec<&str> = Vec::new();
    for line in text.split('\n') {
        if line.trim().is_empty() {
            closed(&mut found, &mut block);
        } else {
            block.push(line);
        }
    }
    closed(&mut found, &mut block);
    found
}

/// Close `block` into `found`, trimmed, unless it holds nothing.
fn closed(found: &mut Vec<String>, block: &mut Vec<&str>) {
    let joined = block.join("\n");
    let trimmed = joined.trim();
    if !trimmed.is_empty() {
        found.push(trimmed.to_owned());
    }
    block.clear();
}

/// Whether `block` is prose rather than a heading, a table, a fence, a tag,
/// an image, a list or a quotation.
pub(super) fn is_prose(block: &str) -> bool {
    !NOT_PROSE.iter().any(|mark| block.starts_with(mark))
}

/// The first sentence of the first prose block of `text`.
pub(super) fn paragraph(text: &str) -> Option<String> {
    blocks(text)
        .into_iter()
        .find(|block| is_prose(block))
        .map(|block| sentence(&block))
        .filter(|found| !found.is_empty())
}

/// The first comment block of `text`, in its first 60 lines, that says
/// something, as one sentence: lines opening with `#` or `//`, without a
/// shebang, the managed marker, a "do not edit" line or an editor
/// directive.
pub(super) fn first_comment(text: &str) -> Option<String> {
    let mut block: Vec<&str> = Vec::new();
    for line in text.lines().take(60) {
        match comment_body(line) {
            Some(body) if is_boilerplate(body) => {}
            Some(body) if !body.is_empty() && !is_directive(body) => block.push(body),
            _ if !block.is_empty() => break,
            _ => {}
        }
    }
    (!block.is_empty())
        .then(|| sentence(&block.join(" ")))
        .filter(|found| !found.is_empty())
}

/// The text of a comment line, `#` and `/` marks and spaces trimmed; None for
/// any other line or a shebang.
fn comment_body(line: &str) -> Option<&str> {
    let stripped = line.trim();
    let comment =
        (stripped.starts_with('#') || stripped.starts_with("//")) && !stripped.starts_with("#!");
    comment.then(|| stripped.trim_start_matches(['#', '/']).trim())
}

/// Whether a comment is the managed marker or a "do not edit" line.
fn is_boilerplate(body: &str) -> bool {
    body.contains(MANAGED) || body.to_lowercase().contains("do not edit")
}

/// Whether a comment is an editor or linter directive.
fn is_directive(body: &str) -> bool {
    body.starts_with("yaml-language-server") || body.starts_with("shellcheck")
}

/// The value of the first line of `text` that opens with `key:`, trimmed,
/// one quote dropped from each end.
pub(super) fn value_of<'text>(text: &'text str, key: &str) -> Option<&'text str> {
    text.lines().find_map(|line| {
        let value = line.strip_prefix(key)?.strip_prefix(':')?.trim();
        let value = value.strip_prefix(['"', '\'']).unwrap_or(value);
        let value = value.strip_suffix(['"', '\'']).unwrap_or(value);
        (!value.is_empty()).then_some(value)
    })
}

/// The first line of a Rust module's doc, `//!`, that says something.
pub(super) fn module_doc(text: &str) -> Option<&str> {
    text.lines().find_map(|line| {
        line.strip_prefix("//!")
            .map(str::trim)
            .filter(|doc| !doc.is_empty())
    })
}

/// The text of the first `# Title` line of `text`.
pub(super) fn title_of(text: &str) -> Option<&str> {
    text.lines().find_map(|line| {
        let rest = line.strip_prefix('#')?;
        rest.starts_with(char::is_whitespace)
            .then(|| rest.trim())
            .filter(|title| !title.is_empty())
    })
}

#[cfg(test)]
mod tests {
    use super::{blocks, first_comment, module_doc, paragraph, sentence, title_of, value_of, wrap};

    #[test]
    fn a_sentence_drops_links_marks_and_what_follows_it() {
        assert_eq!(
            sentence(concat!(
                "The **gate** reads [the rules]",
                "(docs/rules.md) and `ci.yml`. More."
            )),
            "The gate reads the rules and ci.yml"
        );
        assert_eq!(
            sentence("  Spread\nover   lines!  Then more"),
            "Spread over lines!"
        );
        assert_eq!(sentence("[not a link] (spaced)"), "[not a link] (spaced)");
        assert_eq!(sentence("v1.2 ships."), "v1.2 ships");
    }

    #[test]
    fn a_long_sentence_is_cut_at_a_clause_or_a_word() {
        let clause = format!("{}, {}", "word ".repeat(18).trim(), "tail ".repeat(20));
        assert_eq!(sentence(&clause), "word ".repeat(18).trim());
        let words = "alpha ".repeat(30);
        let cut = sentence(&words);
        assert!(
            cut.chars().count() <= 140 && cut.ends_with("alpha"),
            "{cut}"
        );
    }

    #[test]
    fn wrap_breaks_at_eighty_columns_and_indents_what_follows() {
        let wrapped = wrap(&format!("1. {}", "word ".repeat(30)), "   ");
        let lines: Vec<&str> = wrapped.lines().collect();
        assert!(lines.iter().all(|line| line.chars().count() <= 80));
        assert!(lines[1].starts_with("   word"));
        assert_eq!(wrap("keep  two  spaces", ""), "keep  two  spaces");
        let long = format!("short {} end", "x".repeat(90));
        assert_eq!(wrap(&long, ""), format!("short\n{}\nend", "x".repeat(90)));
    }

    #[test]
    fn blocks_split_at_blank_lines_and_paragraphs_skip_headings() {
        let text = "# Title\n\n| a | b |\n\n  First line\nsecond line.  \n \t \nLast.";
        assert_eq!(
            blocks(text),
            ["# Title", "| a | b |", "First line\nsecond line.", "Last."]
        );
        assert_eq!(paragraph(text).unwrap(), "First line second line");
        assert_eq!(paragraph("# Only a title\n"), None);
    }

    #[test]
    fn the_first_comment_skips_markers_and_stops_at_its_end() {
        let text = concat!(
            "#!/bin/sh\n# generated by rust-gate sync; do not edit\n",
            "# shellcheck disable=SC2034\n# What this script does,\n",
            "# over two lines.\n#\n# Another block.\nset -eu\n"
        );
        assert_eq!(
            first_comment(text).unwrap(),
            "What this script does, over two lines"
        );
        assert_eq!(first_comment("set -eu\n"), None);
    }

    #[test]
    fn keys_docs_and_titles_are_read_from_their_lines() {
        assert_eq!(value_of("on: push\nname: \"CI\"\n", "name"), Some("CI"));
        assert_eq!(value_of("names: x\n", "name"), None);
        assert_eq!(module_doc("//!\n//! The module.\n"), Some("The module."));
        assert_eq!(title_of("#!x\n## Sub\n# The title \n"), Some("The title"));
    }
}
