//! LNT-001, the organization's lints: one list, denied in every repository's
//! `[workspace.lints]`, or `[lints]` for a single package, between the markers
//! `rust-gate lints --write` writes, so an editor shows the errors the gate
//! raises; and the thresholds of the organization's `clippy.toml`. A
//! repository may add lints below the markers and tighten a threshold; it may
//! remove, lower or loosen none.
//!
//! Naming, NAME's share of the list: `nonstandard_style` holds the case of
//! every name, `PascalCase` types, `snake_case` functions and modules,
//! `SCREAMING_SNAKE_CASE` constants; `allow_attributes` refuses an `#[allow]`
//! that would lift it. `same_name_method` refuses an inherent method named like
//! a trait's. The Rust API Guidelines' naming conventions are already denied
//! through `clippy::all` and `clippy::pedantic`: `wrong_self_convention` for
//! `as_`, `to_` and `into_`, `new_ret_no_self`, `should_implement_trait`,
//! `enum_variant_names`, `iter_not_returning_iterator` and `struct_field_names`
//! among them.
//!
//! Left out on purpose: `module_name_repetitions` and `similar_names`, too many
//! false positives; `redundant_pub_crate`, which contradicts `unreachable_pub`;
//! `arithmetic_side_effects`, `exhaustive_enums`, `exhaustive_structs`,
//! `missing_docs_in_private_items`, `missing_assert_message`,
//! `tests_outside_test_module` and the `shadow_*` lints, each a house style
//! rather than a defect; `renamed_function_params`, which demands a trait's
//! parameter names, such as the `f` of `fmt` that `min_ident_chars` refuses;
//! `print_stdout`, which LIB-001 holds for libraries only; and `unsafe_code`,
//! which the `quality` step denies or not per `unsafe-policy`.

use crate::runner::{Cmd, Failure};
use std::fmt::Write as _;
use std::path::Path;

/// The line that opens the block `rust-gate lints --write` owns.
pub(crate) const BEGIN: &str =
    "# generated by rust-gate lints --write; do not edit down to the end marker";

/// The line that closes it.
pub(crate) const END: &str =
    "# end of the generated lints; add the repository's own below, never remove one";

/// Lint groups: denied beneath the single lints, so one lint can be set
/// against its group.
const GROUPS: &[&str] = &[
    "clippy::all",
    "clippy::pedantic",
    "clippy::cargo",
    "rust::rust_2018_idioms",
    "rust::nonstandard_style",
];

/// Single lints, each denied.
const DENIED: &[&str] = &[
    "clippy::allow_attributes",
    "clippy::allow_attributes_without_reason",
    "clippy::unwrap_used",
    "clippy::expect_used",
    "clippy::panic",
    "clippy::indexing_slicing",
    "clippy::unreachable",
    "clippy::exit",
    "clippy::todo",
    "clippy::unimplemented",
    "clippy::dbg_macro",
    "clippy::self_named_module_files",
    "clippy::absolute_paths",
    "clippy::min_ident_chars",
    "clippy::redundant_test_prefix",
    "clippy::ignore_without_reason",
    "clippy::should_panic_without_expect",
    "clippy::undocumented_unsafe_blocks",
    "clippy::cognitive_complexity",
    "clippy::excessive_nesting",
    "clippy::same_name_method",
    "rust::missing_docs",
    "rust::unreachable_pub",
    "rust::missing_debug_implementations",
    "rust::unused_qualifications",
    "rust::let_underscore_drop",
    "rust::redundant_lifetimes",
    "rust::unit_bindings",
    "rust::unexpected_cfgs",
];

/// Lints a group denies that the organization allows: DEP-001 owns duplicate
/// versions, with its exceptions, and similar names are too often right.
const ALLOWED: &[&str] = &["clippy::multiple_crate_versions", "clippy::similar_names"];

/// The thresholds of `clippy.toml`, where a lower number is stricter.
pub(crate) const THRESHOLDS: &[(&str, u32)] = &[
    ("cognitive-complexity-threshold", 15),
    ("too-many-lines-threshold", 100),
    ("too-many-arguments-threshold", 5),
    ("excessive-nesting-threshold", 4),
    ("absolute-paths-max-segments", 2),
];

/// The allowances of `clippy.toml`, where `false` is stricter: test code may
/// unwrap, expect, panic, index and print, and may not leave a `dbg!`.
pub(crate) const ALLOWANCES: &[(&str, bool)] = &[
    ("allow-unwrap-in-tests", true),
    ("allow-expect-in-tests", true),
    ("allow-panic-in-tests", true),
    ("allow-indexing-slicing-in-tests", true),
    ("allow-print-in-tests", true),
    ("allow-dbg-in-tests", false),
];

/// Each lint the root manifest sets, `tool::name`, a tab, and its level.
const LEVELS: &str = "(.workspace.lints // .lints // {}) | to_entries[] \
    | select(.value | type == \"object\") | .key as $tool | .value | to_entries[] \
    | [$tool + \"::\" + .key, (if (.value | type) == \"object\" then .value.level \
    else .value end)] | @tsv";

/// Each key of a `clippy.toml`, a tab, and its value.
const SETTINGS: &str = "to_entries[] | [.key, (.value | tostring)] | @tsv";

/// The block for a manifest: `[workspace.lints]` for a workspace root,
/// `[lints]` for a single package, between the markers.
pub(crate) fn lint_block(workspace: bool) -> String {
    let table = if workspace {
        "[workspace.lints]"
    } else {
        "[lints]"
    };
    let mut block = format!("{BEGIN}\n{table}\n");
    let key = |lint: &str| lint.replacen("::", ".", 1);
    for lint in GROUPS {
        let _ = writeln!(
            block,
            "{} = {{ level = \"deny\", priority = -1 }}",
            key(lint)
        );
    }
    for (lint, level) in DENIED
        .iter()
        .map(|lint| (lint, "deny"))
        .chain(ALLOWED.iter().map(|lint| (lint, "allow")))
    {
        let _ = writeln!(block, "{} = \"{level}\"", key(lint));
    }
    block.push_str(END);
    block.push('\n');
    block
}

/// The organization's `clippy.toml` settings, every threshold then every
/// allowance.
pub(crate) fn clippy_config() -> String {
    let mut text = String::new();
    for (key, value) in THRESHOLDS {
        let _ = writeln!(text, "{key} = {value}");
    }
    for (key, value) in ALLOWANCES {
        let _ = writeln!(text, "{key} = {value}");
    }
    text
}

/// `manifest` with the block written in: in place of the one between the
/// markers, or appended when there is none. A manifest that sets lints
/// outside the markers is refused, since TOML cannot hold one table twice.
pub(crate) fn with_lint_block(manifest: &str, workspace: bool) -> Result<String, String> {
    let block = lint_block(workspace);
    if let Some((before, from_block)) = manifest.split_once(BEGIN) {
        let (_, after) = from_block
            .split_once(END)
            .ok_or("the generated lints open with their marker and never close")?;
        let rest = after.strip_prefix('\n').unwrap_or(after);
        return Ok(format!("{before}{block}{rest}"));
    }
    let tables = manifest.lines().map(str::trim).find(|line| {
        ["[lints", "[workspace.lints"]
            .iter()
            .any(|prefix| line.starts_with(prefix))
    });
    if let Some(table) = tables {
        return Err(format!(
            "the manifest already sets lints in `{table}`; remove that table, run this again, \
             then add the lints the organization does not hold below the generated block"
        ));
    }
    let separator = if manifest.ends_with("\n\n") || manifest.is_empty() {
        ""
    } else if manifest.ends_with('\n') {
        "\n"
    } else {
        "\n\n"
    };
    Ok(format!("{manifest}{separator}{block}"))
}

/// Each lint the manifest at `manifest` sets and its level, read through jaq.
pub(crate) fn manifest_lint_levels(manifest: &Path) -> Result<Vec<(String, String)>, Failure> {
    let listing = Cmd::new("jaq --from toml -r")
        .arg(LEVELS)
        .arg(manifest)
        .capture()?;
    Ok(pairs(&listing))
}

/// Each key the `clippy.toml` at `config` sets and its value, read through jaq.
pub(crate) fn clippy_settings_of(config: &Path) -> Result<Vec<(String, String)>, Failure> {
    let listing = Cmd::new("jaq --from toml -r")
        .arg(SETTINGS)
        .arg(config)
        .capture()?;
    Ok(pairs(&listing))
}

/// Tab-separated pairs, one per line.
fn pairs(listing: &str) -> Vec<(String, String)> {
    listing
        .lines()
        .filter_map(|line| line.split_once('\t'))
        .map(|(key, value)| (key.to_owned(), value.to_owned()))
        .collect()
}

/// The organization's lints `levels` leaves short of `deny`, in list order.
pub(crate) fn undenied(levels: &[(String, String)]) -> Vec<&'static str> {
    GROUPS
        .iter()
        .chain(DENIED)
        .copied()
        .filter(|lint| {
            !levels
                .iter()
                .any(|(name, level)| name == lint && matches!(level.as_str(), "deny" | "forbid"))
        })
        .collect()
}

/// What `settings` leaves looser than the organization's `clippy.toml`: a
/// key missing, a threshold raised or an allowance granted, one line each.
pub(crate) fn looser_settings(settings: &[(String, String)]) -> Vec<String> {
    let value = |key: &str| {
        settings
            .iter()
            .find(|(name, _)| name == key)
            .map(|(_, value)| value.as_str())
    };
    let mut found = Vec::new();
    for (key, floor) in THRESHOLDS {
        match value(key).map(str::parse::<u32>) {
            None => found.push(format!("`{key}` is not set; the organization sets {floor}")),
            Some(Ok(number)) if number <= *floor => {}
            Some(_) => found.push(format!(
                "`{key}` is {}, looser than the organization's {floor}",
                value(key).unwrap_or_default()
            )),
        }
    }
    for (key, allowed) in ALLOWANCES {
        match value(key) {
            None => found.push(format!(
                "`{key}` is not set; the organization sets {allowed}"
            )),
            Some("false") => {}
            Some("true") if *allowed => {}
            Some(other) => found.push(format!(
                "`{key}` is {other}, looser than the organization's {allowed}"
            )),
        }
    }
    found
}

#[cfg(test)]
mod tests {
    use super::{
        ALLOWANCES, BEGIN, END, THRESHOLDS, lint_block, looser_settings, undenied, with_lint_block,
    };

    /// `(key, value)` pairs from `key=value` words.
    fn settings(words: &str) -> Vec<(String, String)> {
        words
            .split_whitespace()
            .filter_map(|word| word.split_once('='))
            .map(|(key, value)| (key.to_owned(), value.to_owned()))
            .collect()
    }

    #[test]
    fn the_block_denies_every_lint_under_its_table() {
        let block = lint_block(true);
        assert!(block.starts_with(&format!("{BEGIN}\n[workspace.lints]\n")));
        assert!(block.ends_with(&format!("{END}\n")));
        assert!(block.contains("clippy.pedantic = { level = \"deny\", priority = -1 }\n"));
        assert!(block.contains("clippy.unwrap_used = \"deny\"\n"));
        assert!(block.contains("rust.missing_docs = \"deny\"\n"));
        assert!(block.contains("rust.nonstandard_style = { level = \"deny\", priority = -1 }\n"));
        assert!(block.contains("clippy.same_name_method = \"deny\"\n"));
        assert!(block.contains("clippy.multiple_crate_versions = \"allow\"\n"));
        assert!(lint_block(false).contains("\n[lints]\n"));
    }

    #[test]
    fn the_block_replaces_its_old_self_or_lands_at_the_end() {
        let manifest = "[package]\nname = \"a\"\n";
        let written = with_lint_block(manifest, false).unwrap();
        assert_eq!(written, format!("{manifest}\n{}", lint_block(false)));
        let stale = written.replace("clippy.panic = \"deny\"\n", "") + "clippy.own = \"deny\"\n";
        assert_eq!(
            with_lint_block(&stale, false).unwrap(),
            format!("{written}clippy.own = \"deny\"\n")
        );
        assert!(with_lint_block(&format!("{BEGIN}\n"), false).is_err());
        let refused = with_lint_block("[lints.clippy]\npanic = \"deny\"\n", false).unwrap_err();
        assert!(refused.starts_with("the manifest already sets lints in `[lints.clippy]`"));
    }

    #[test]
    fn a_lint_short_of_deny_is_named() {
        let mut levels: Vec<(String, String)> = lint_block(false)
            .lines()
            .filter_map(|line| line.split_once(" = "))
            .map(|(key, _)| (key.replacen('.', "::", 1), "deny".to_owned()))
            .collect();
        assert!(undenied(&levels).is_empty());
        levels.retain(|(name, _)| name != "clippy::panic");
        levels.push(("rust::missing_docs".to_owned(), "warn".to_owned()));
        levels.retain(|(name, level)| name != "rust::missing_docs" || level == "warn");
        assert_eq!(undenied(&levels), ["clippy::panic", "rust::missing_docs"]);
    }

    #[test]
    fn a_threshold_raised_or_an_allowance_granted_is_looser() {
        let generated: Vec<(String, String)> = THRESHOLDS
            .iter()
            .map(|(key, value)| ((*key).to_owned(), value.to_string()))
            .chain(
                ALLOWANCES
                    .iter()
                    .map(|(key, value)| ((*key).to_owned(), value.to_string())),
            )
            .collect();
        assert!(looser_settings(&generated).is_empty());
        let mut tighter = generated.clone();
        tighter[1].1 = "80".to_owned();
        assert!(looser_settings(&tighter).is_empty());
        let loose = settings(
            "cognitive-complexity-threshold=25 too-many-lines-threshold=100 \
             too-many-arguments-threshold=5 excessive-nesting-threshold=4 \
             absolute-paths-max-segments=2 allow-unwrap-in-tests=true \
             allow-expect-in-tests=true allow-panic-in-tests=true \
             allow-indexing-slicing-in-tests=true allow-print-in-tests=true \
             allow-dbg-in-tests=true",
        );
        assert_eq!(
            looser_settings(&loose),
            [
                "`cognitive-complexity-threshold` is 25, looser than the organization's 15",
                "`allow-dbg-in-tests` is true, looser than the organization's false",
            ]
        );
        assert_eq!(
            looser_settings(&[]).first().map(String::as_str),
            Some("`cognitive-complexity-threshold` is not set; the organization sets 15")
        );
    }
}
