//! The organization's configuration of the tools the gate runs, passed at
//! run time rather than copied into every repository: rustfmt's options on
//! its command line, and Clippy's thresholds written under the run's
//! temporary directory and named by `CLIPPY_CONF_DIR`. A file that still
//! opens with [`HEADER`] is an earlier copy `rust-gate sync` wrote, and is
//! not the repository's own.

use crate::checks::lint_policy::clippy_config;
use crate::runner::Failure;
use std::fs;
use std::path::{Path, PathBuf};

/// The line every file `rust-gate sync` writes opens with.
pub(crate) const HEADER: &str = "# generated by rust-gate sync; do not edit\n";

/// rustfmt's options, as `--config` takes them: the 2024 style.
pub(crate) const RUSTFMT_OPTIONS: &str = "style_edition=2024";

/// Whether the file at `path` opens with [`HEADER`]: written by
/// `rust-gate sync`, not by the repository.
pub(crate) fn is_generated(path: &Path) -> bool {
    fs::read_to_string(path).is_ok_and(|text| text.starts_with(HEADER))
}

/// The `clippy.toml` Clippy reads for the workspace at `root`: the nearest
/// one walking up to the repository root `workspace`.
pub(crate) fn nearest_clippy_config(root: &Path, workspace: &Path) -> Option<PathBuf> {
    root.ancestors()
        .take_while(|directory| directory.starts_with(workspace))
        .flat_map(|directory| ["clippy.toml", ".clippy.toml"].map(|name| directory.join(name)))
        .find(|file| file.is_file())
}

/// The directory `CLIPPY_CONF_DIR` names for the project at `project` in the
/// repository at `workspace`: one under `temp` holding the organization's
/// `clippy.toml`, or none when the repository commits a `clippy.toml` of its
/// own, which the source rules hold no looser than the organization's.
pub(crate) fn clippy_directory(
    project: &Path,
    workspace: &Path,
    temp: &Path,
) -> Result<Option<PathBuf>, Failure> {
    if nearest_clippy_config(project, workspace).is_some_and(|file| !is_generated(&file)) {
        return Ok(None);
    }
    let directory = temp.join("clippy-config");
    fs::create_dir_all(&directory)
        .map_err(|error| format!("cannot create {}: {error}", directory.display()))?;
    let file = directory.join("clippy.toml");
    fs::write(&file, clippy_config())
        .map_err(|error| format!("cannot write {}: {error}", file.display()))?;
    Ok(Some(directory))
}

#[cfg(test)]
mod tests {
    use super::{HEADER, clippy_directory, is_generated, nearest_clippy_config};
    use std::env;
    use std::fs;
    use std::process;

    #[test]
    fn the_nearest_clippy_toml_inside_the_repository_is_read() {
        let root = env::temp_dir().join(format!("nearest-clippy-{}", process::id()));
        let project = root.join("crates/app");
        fs::create_dir_all(&project).unwrap();
        assert_eq!(nearest_clippy_config(&project, &root), None);
        fs::write(root.join("clippy.toml"), "").unwrap();
        assert_eq!(
            nearest_clippy_config(&project, &root),
            Some(root.join("clippy.toml"))
        );
        fs::write(project.join(".clippy.toml"), "").unwrap();
        assert_eq!(
            nearest_clippy_config(&project, &root),
            Some(project.join(".clippy.toml"))
        );
        fs::remove_dir_all(&root).unwrap();
    }

    #[test]
    fn clippy_reads_the_organization_config_unless_the_repository_writes_its_own() {
        let root = env::temp_dir().join(format!("clippy-directory-{}", process::id()));
        let temp = root.join("temp");
        fs::create_dir_all(&temp).unwrap();
        let written = clippy_directory(&root, &root, &temp).unwrap().unwrap();
        let config = fs::read_to_string(written.join("clippy.toml")).unwrap();
        assert!(
            config.contains("too-many-lines-threshold = 100\n"),
            "{config}"
        );
        fs::write(root.join("clippy.toml"), format!("{HEADER}a = 1\n")).unwrap();
        assert!(is_generated(&root.join("clippy.toml")));
        assert!(clippy_directory(&root, &root, &temp).unwrap().is_some());
        fs::write(root.join("clippy.toml"), "too-many-lines-threshold = 50\n").unwrap();
        assert!(!is_generated(&root.join("clippy.toml")));
        assert_eq!(clippy_directory(&root, &root, &temp).unwrap(), None);
        fs::remove_dir_all(&root).unwrap();
    }
}
